In [1]:
!pip install vnstock
!pip install vnstock3 --upgrade

Requirement already satisfied: vnstock in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (3.4.2)
Requirement already satisfied: requests in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (2.32.5)
Requirement already satisfied: beautifulsoup4 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (4.14.3)
Requirement already satisfied: pandas in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (2.3.2)
Requirement already satisfied: seaborn in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (0.13.2)
Requirement already satisfied: openpyxl in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (3.1.5)
Requirement already satisfied: pydantic in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (2.8.2)
Requirement already satisfied: psutil in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (7.2.2)
Requirement already satisfied: packaging>=20.0 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (26.0)
Requirement already satisfied: importlib-metadata>=1.0 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (6.11.0)
Requirement already satisfied: tenacity in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (8.5.0)
Requirement already satisfied: vnai>=2.3.9 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (2.3.9)
Requirement already satisfied: vnstock_ezchart>=0.0.3 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock) (0.0.3)
Requirement already satisfied: zipp>=0.5 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from importlib-metadata>=1.0->vnstock) (3.23.0)
Requirement already satisfied: cffi>=1.17.1 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnai>=2.3.9->vnstock) (2.0.0)
Requirement already satisfied: pycparser in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.17.1->vnai>=2.3.9->vnstock) (3.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from requests->vnstock) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from requests->vnstock) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from requests->vnstock) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from requests->vnstock) (2026.2.25)
Requirement already satisfied: squarify in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock_ezchart>=0.0.3->vnstock) (0.4.4)
Requirement already satisfied: wordcloud in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock_ezchart>=0.0.3->vnstock) (1.9.6)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4->vnstock) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4->vnstock) (4.15.0)
Requirement already satisfied: et-xmlfile in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from openpyxl->vnstock) (2.0.0)
Requirement already satisfied: numpy>=1.22.4 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from pandas->vnstock) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from pandas->vnstock) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from pandas->vnstock) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from pandas->vnstock) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas->vnstock) (1.17.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from pydantic->vnstock) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from pydantic->vnstock) (2.20.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from seaborn->vnstock) (3.10.7)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (1.4.9)
Requirement already satisfied: pillow>=8 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (10.4.0)
Requirement already satisfied: pyparsing>=3 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (3.2.5)
Requirement already satisfied: vnstock3 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (3.2.1)
Requirement already satisfied: requests in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock3) (2.32.5)
Requirement already satisfied: beautifulsoup4 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock3) (4.14.3)
Requirement already satisfied: pandas in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock3) (2.3.2)
Requirement already satisfied: vnai>=2.0 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock3) (2.3.9)
Requirement already satisfied: openpyxl in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock3) (3.1.5)
Requirement already satisfied: pydantic in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock3) (2.8.2)
Requirement already satisfied: psutil in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock3) (7.2.2)
Requirement already satisfied: fake_useragent in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock3) (2.2.0)
Requirement already satisfied: vnstock_ezchart in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock3) (0.0.3)
Requirement already satisfied: click in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock3) (8.3.1)
Requirement already satisfied: seaborn in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock3) (0.13.2)
Requirement already satisfied: cffi>=1.17.1 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnai>=2.0->vnstock3) (2.0.0)
Requirement already satisfied: pycparser in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.17.1->vnai>=2.0->vnstock3) (3.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from requests->vnstock3) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from requests->vnstock3) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from requests->vnstock3) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from requests->vnstock3) (2026.2.25)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4->vnstock3) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from beautifulsoup4->vnstock3) (4.15.0)
Requirement already satisfied: colorama in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from click->vnstock3) (0.4.6)
Requirement already satisfied: et-xmlfile in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from openpyxl->vnstock3) (2.0.0)
Requirement already satisfied: numpy>=1.22.4 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from pandas->vnstock3) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from pandas->vnstock3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from pandas->vnstock3) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from pandas->vnstock3) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas->vnstock3) (1.17.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from pydantic->vnstock3) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from pydantic->vnstock3) (2.20.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from seaborn->vnstock3) (3.10.7)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock3) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock3) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock3) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock3) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock3) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock3) (10.4.0)
Requirement already satisfied: pyparsing>=3 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock3) (3.2.5)
Requirement already satisfied: squarify in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock_ezchart->vnstock3) (0.4.4)
Requirement already satisfied: wordcloud in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock_ezchart->vnstock3) (1.9.6)
Requirement already satisfied: vnstock>=3.2.7 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock_ezchart->vnstock3) (3.4.2)
Requirement already satisfied: importlib-metadata>=1.0 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock>=3.2.7->vnstock_ezchart->vnstock3) (6.11.0)
Requirement already satisfied: tenacity in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from vnstock>=3.2.7->vnstock_ezchart->vnstock3) (8.5.0)
Requirement already satisfied: zipp>=0.5 in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (from importlib-metadata>=1.0->vnstock>=3.2.7->vnstock_ezchart->vnstock3) (3.23.0)

In [2]:
!pip install numpy pandas os

Requirement already satisfied: numpy in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (2.2.6)
Requirement already satisfied: pandas in c:\users\pc\appdata\local\programs\python\python310\lib\site-packages (2.3.2)

ERROR: Could not find a version that satisfies the requirement os (from versions: none)
ERROR: No matching distribution found for os

In [3]:

import os
import numpy as np
import pandas as pd
from vnstock import Listing, Vnstock

# Thiết lập API key trong biến môi trường
os.environ['VNSTOCK_API_KEY'] = 'vnstock_63c337138534f5000b298d47f4765c48'

# Khởi tạo đối tượng Vnstock mà không cần truyền api_key vào constructor
stock = Vnstock()

# Tiến hành các yêu cầu API như bình thường
stock_data = stock.stock(symbol="NVL", source="VCI")

# Hiển thị dữ liệu

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", 200)

display(stock_data.finance.balance_sheet(period="year", lang="vi", dropna=True))
display(stock_data.finance.income_statement(period="year", lang="vi", dropna=True))
display(stock_data.finance.cash_flow(period="year", lang="vi", dropna=True))
display(stock_data.finance.ratio(period="year", lang="vi", dropna=True))

,CP,Năm,TÀI SẢN NGẮN HẠN (đồng),Tiền và tương đương tiền (đồng),Giá trị thuần đầu tư ngắn hạn (đồng),Các khoản phải thu ngắn hạn (đồng),Hàng tồn kho ròng,Tài sản lưu động khác,TÀI SẢN DÀI HẠN (đồng),Phải thu về cho vay dài hạn (đồng),Tài sản cố định (đồng),Giá trị ròng tài sản đầu tư,Đầu tư dài hạn (đồng),Lợi thế thương mại,Tài sản dài hạn khác,TỔNG CỘNG TÀI SẢN (đồng),NỢ PHẢI TRẢ (đồng),Nợ ngắn hạn (đồng),Nợ dài hạn (đồng),VỐN CHỦ SỞ HỮU (đồng),Vốn và các quỹ (đồng),Lãi chưa phân phối (đồng),LỢI ÍCH CỦA CỔ ĐÔNG THIỂU SỐ,TỔNG CỘNG NGUỒN VỐN (đồng),Trả trước cho người bán ngắn hạn (đồng),Phải thu về cho vay ngắn hạn (đồng),"Hàng tồn kho, ròng (đồng)",Tài sản lưu động khác (đồng),Cổ phiếu phổ thông (đồng),Vốn góp của chủ sở hữu (đồng),Vay và nợ thuê tài chính dài hạn (đồng),Người mua trả tiền trước ngắn hạn (đồng),Vay và nợ thuê tài chính ngắn hạn (đồng),Lợi thế thương mại (đồng),Trả trước dài hạn (đồng),Tài sản dài hạn khác (đồng),Phải thu dài hạn khác (đồng),Phải thu dài hạn (đồng)
0,NVL,2025,207242734850379,4395320969838,53843467143,47320440385793,153391641828133,2081488199472,42549576635974,2879396000000,1900525281486,5151243697334,5292774070428,0,3234295985093,249792311486353,190942057522363,95907964304638,95034093217725,58850253963990,58850253963990,16932105487226,13554575453125,249792311486353,8157531648147,13339562455419,153812142804224,0,22320185490000,22320185490000,35672724217510,20353028512829,31518046299679,1639299616147,1438453388297,301440514598,23683250407407,26546144407407
1,NVL,2024,207831078798684,4607601921683,31258216194,54813392824915,146607440687432,1771385148460,29946901858972,176200000000,1937682347954,5737179048000,1709377159826,0,4117663424757,237777980657656,190486956299042,107222351548398,83264604750644,47291024358614,47291024358614,13281118742079,9457258311909,237777980657656,7857833385978,6050897395010,147027941663523,0,19501045380000,19501045380000,24587656403178,18915181304285,36978198251788,2475838484574,1500140582061,302340514598,15741300378910,15900998378910
2,NVL,2023,191154819021853,3412524436724,43507843256,47011035493822,138935271807965,1752479440086,50331560521272,176200000000,2401389820394,5543248882224,1728050951949,0,5570133515394,241486379543125,196183529500722,87282658320119,108900871180603,45302850042403,45302850042403,13494207570271,7255995167506,241486379543125,7457550110086,6602402331194,139096217236865,0,19501045380000,19501045380000,26774936365837,19114956528914,30937469509389,3696777259435,1689485786703,304914914598,34297901289784,34560075860276
3,NVL,2022,198114675000040,8600170523502,326704693300,52345590760029,134955711974239,1886497048970,59620201167981,98000000000,3936964957063,3140889237220,1615915212089,0,6271513013007,257734876168021,212917145787856,78174120549026,134743025238830,44817730380165,44817730380165,12888775711396,7376307364143,257734876168021,8050596939825,4466826766847,134957802212263,0,19501045380000,19501045380000,35666512929989,15962589533396,29202383656301,4544317395119,1575118212493,33839750000,43984065347630,44081959918122
4,NVL,2021,156048716497795,17249156145556,837023156881,26409499239024,110156937437285,1396100519049,45784830488255,234500000000,1441727882314,2754183434458,1624040896080,0,6089837697056,201833546986050,160660433654081,49214830460474,111445603193607,41173113331969,41173113331969,10707524273613,6138150553730,201833546986050,2332779900869,6303352180537,110159027675309,0,19304213190000,19304213190000,41430753323566,8305600061137,19087653178619,5104024245116,828185441183,25349750000,33347755804142,33582150374634
5,NVL,2020,114203561614442,11558787555672,721829853961,13797994628756,86864906421772,1260043154281,30332784019580,175500000000,1218441600419,2824247750920,1891042286029,0,6469509877688,144536345634022,112604198448315,31427343626571,81176854821744,31932147185707,31932147185707,12051422037059,6047612897622,144536345634022,1466925680402,3019394229338,86867908152180,0,9862852970000,9862852970000,34357216078896,4087250768389,14544114172196,0,419763171833,9649750000,17468272978338,17643772978338
6,NVL,2019,71194821173128,6466219516377,466222941609,5894052885444,57205793200220,1162532629478,18784421425391,0,840044553105,3798441570836,5744314191185,0,7180794229076,89979242598519,65518168766672,18809633988008,46708534778664,24461073831847,24461073831847,8722828720589,2182647360232,89979242598519,833905092647,768720953764,57209437130190,0,9695407970000,9695407970000,26145644448493,1254023590387,8444638010326,6841457940364,262799866843,7939750000,370739066748,370739066748
7,NVL,2018,50081021580369,12315170763611,95691805879,5621529636151,31122887148542,925742226186,19041105364812,0,755850432888,3056785356717,7702903772477,0,6839982377635,69122126945181,49152327254974,27995143422573,21157183832401,19969799690207,19969799690207,5618698169829,981494999352,69122126945181,1423446698518,430653870350,31130466196468,0,9304466740000,9372766740000,16262686196964,7779944907345,11645389730077,6355909039839,414115027558,7939750000,255403896052,255403896052
8,NVL,2017,41165965853502,6650160994741,512509850676,5998164901016,27128796867411,876333239658,8300996138739,449644400000,326609439362,2944616534199,1042972935246,0,2971362895384,49466961992241,36210571488821,22658196187952,13552375300869,13256390503420,13256390503420,2907218106652,645753611368,49466961992241,1771344474280,625605206171,27136318547663,0,6428287880000,6496587880000,10200873745673,8848256383261,7748878980646,2406227189374,449352171677,0,203803366742,654401516832
9,NVL,2016,30288729450391,3336969432791,964822616829,9635748057226,15789641948072,561547395473,6238346263606,0,148823215155,1945013110252,374785832914,0,2572552491341,36527075713997,26480185576926,15011223881816,11468961695110,10046890137071,10046890137071,952449830514,958421521157,36527075713997,936793642253,3313658593511,15795037614256,0,5893692340000,5961992340000,7907493558081,5954806119381,5595769743653,2217606029051,288077446389,3115200000,911018553261,911972303351
10,NVL,2015,18133289908529,3859710163282,818888056357,6058945996358,7158828473488,236917219044,8437118726515,0,87792452983,1082785523673,1581877669261,1119884733917,186263593828,26570408635044,20475199219618,13354623721526,7120575498092,6095209415426,6095209415426,550370777697,979282422321,26570408635044,283928585866,1267616016535,7201718027433,0,3504657610000,3682957610000,5480587851378,8146870114590,2513142521645,0,160651074570,55643750000,3309216386210,3309363386210
11,NVL,2014,14353286656692,2779414633352,206475016934,3135397176229,8151084883345,80914946832,1740423717632,0,69038509465,394784440061,20879773973,102371310691,102342301579,16093710374324,12731365085373,9906274227168,2825090858205,3362345288951,3362345288951,331007731063,695618952488,16093710374324,603546276742,554076856364,8159526518567,0,2300000000000,2300000000000,2020351873578,3441450179630,1645839010685,0,97148602621,5092000000,965231818962,965231818962
12,NVL,2013,7565139355598,248980514988,148035131589,1288348567485,5837374366239,42400775297,1262625731318,0,122891690589,645567858867,62522481345,0,425643700517,8827765086916,7388996568112,4923606860286,2465389707826,878500725525,878500725525,237311605725,0,8827765086916,637041447597,0,5840196239155,946822767,1200000000000,1200000000000,2266305717363,1941079014136,1647166033470,0,13685316399,300000,0,6000000000

,CP,Năm,Tăng trưởng doanh thu (%),Doanh thu (đồng),Lợi nhuận sau thuế của Cổ đông công ty mẹ (đồng),Tăng trưởng lợi nhuận (%),Thu nhập tài chính,Chi phí tiền lãi vay,Doanh thu bán hàng và cung cấp dịch vụ,Các khoản giảm trừ doanh thu,Doanh thu thuần,Giá vốn hàng bán,Lãi gộp,Chi phí tài chính,Lãi/lỗ từ công ty liên doanh,Chi phí bán hàng,Chi phí quản lý DN,Lãi/Lỗ từ hoạt động kinh doanh,Thu nhập khác,"Lãi lỗ trong công ty liên doanh, liên kết",Thu nhập/Chi phí khác,Lợi nhuận khác,LN trước thuế,Chi phí thuế TNDN hiện hành,Chi phí thuế TNDN hoãn lại,Lợi nhuận thuần,Cổ đông thiểu số,Cổ đông của Công ty mẹ
0,NVL,2025,-0.232792,6965954941153,1700258456653,1.263411,3188354783746,-147219470559,6965954941153,-607525088,6965347416065,-2477478283690,4487869132375,-3779455581668,22163979297,-610994632473,-1282431888847,2025505792430,2174296259946,0,-1209081637454,965214622492,2990720414922,33341092733,-1205390411317,1818671096338,118412639685,1700258456653
1,NVL,2024,0.903504,9079619602216,-6454779904770,-11.658871,5940883938532,-291396806443,9079619602216,-6244128255,9073375473961,-8989801418151,83574055810,-4710868236963,-6155240237,-533971724119,-1449937734036,-676474941013,405929354905,0,-2285118688241,-1879189333336,-2555664274349,-861820090664,-977157838690,-4394642203703,2060137701067,-6454779904770
2,NVL,2023,-0.572230,4769950330281,605578220113,-0.719908,5128130127876,-327706664781,4769950330281,-13048116461,4756902213820,-3434694564513,1322207649307,-3244008255570,-151539424738,-291975056813,-1490226089162,1272588950900,1075033533475,0,-348740792825,726292740650,1998881691550,-408200850882,-1104816315770,485864524898,-119713695215,605578220113
3,NVL,2022,-0.254996,11150728886696,2162071222708,-0.329525,5004795281883,-844309872037,11150728886696,-16498408971,11134230477725,-6882741523343,4251488954382,-4148522226595,3622528857,-960131278956,-1536210395675,2615042863896,1668784014492,0,-301760530356,1367023484136,3982066348032,-778709166202,-1021826971234,2181530210596,19458987888,2162071222708
4,NVL,2021,1.855418,14967335269790,3224687028176,-0.177181,3644645699649,-514315367150,14967335269790,-64575384077,14902759885713,-8767152197042,6135607688671,-3852245469584,284218826,-1291095498588,-1325621428707,3311575210267,2381546814672,0,-606898860489,1774647954183,5086223164450,-1322966306295,-308504019243,3454752838912,230065810736,3224687028176
5,NVL,2020,-0.524613,5241732045264,3919071634099,0.142110,6210337779881,-566129859176,5241732045264,-215373635826,5026358409438,-3193479439283,1832878970155,-1537268550611,-2552533101,-164007104072,-1290197237197,5049191325055,325517674148,0,-725686652892,-400168978744,4649022346311,-280426493741,-462094272894,3906501579676,-12570054423,3919071634099
6,NVL,2019,-0.294786,11026232997553,3431431162442,0.059450,1027208421374,-1145609766192,11026232997553,-95249885633,10930983111920,-7779325178076,3151657933844,-2084714480224,-9578783868,-294869082499,-1197219171605,592484837022,3847134745198,0,-167283905748,3679850839450,4272335676472,-692528132718,-192385441843,3387422101911,-44009060531,3431431162442
7,NVL,2018,0.329601,15635304112693,3238878304013,0.592775,1296606693933,-1383337897930,15635304112693,-345027380300,15290276732393,-10132300385714,5157976346679,-1932436059562,1318760717206,-424217309126,-727814339948,4688876049182,71219801005,0,-74481539950,-3261738945,4685614310237,-986171527219,-420493495532,3278949287486,40070983473,3238878304013
8,NVL,2017,0.595692,11759393956148,2033481810322,0.221254,1696524125589,-1205387997120,11759393956148,-127057926975,11632336029173,-8375505074901,3256830954272,-1463309502095,12079426593,-258292397030,-676193753758,2567638853571,62422616018,0,-41562445470,20860170548,2588499024119,-810647531519,283791739656,2061643232256,28161421934,2033481810322
9,NVL,2016,0.101132,7369463145396,1665077557360,3.008153,2523042548253,-863073263518,7369463145396,-10282224581,7359180920815,-5776101411561,1583079509254,-1115230030171,498537487,-165484975281,-641600989722,2184304599820,44524814573,0,-39125801538,5399013035,2189703612855,-327371479437,-202982820440,1659349312978,-5728244382,1665077557360
10,NVL,2015,1.375778,6692627652016,415422664012,3.433723,334610510102,-351425428041,6692627652016,-19192626026,6673435025990,-5333572153182,1339862872808,-440474549151,992746135,-238914350343,-359824463054,636252766497,32757004998,0,-60896807714,-28139802716,608112963781,-204312351202,37959337948,441759950527,26337286515,415422664012
11,NVL,2014,0.760204,2817025925662,93696125338,11.848416,60441149247,-134768642888,2817025925662,-15215239979,2801810685683,-2326439908411,475370777272,-188275019428,588463940,-126412978255,-105086584754,116625808022,20919082816,0,-7236216960,13682865856,130308673878,-32465521262,-1663242430,96179910186,2483784848,93696125338
12,NVL,2013,0.000000,1600397507425,7292426121,0.000000,22428580931,-194282057122,1600397507425,0,1600397507425,-1279848252047,320549255378,-217556785040,0,-63645090903,-50859101722,10916858644,13648971056,-1867200886,-5700723265,7948247791,16997905549,-9014903985,-424394684,7558606880,266180759,7292426121

,CP,Năm,Lãi/Lỗ ròng trước thuế,Khấu hao TSCĐ,Dự phòng RR tín dụng,Lãi/Lỗ chênh lệch tỷ giá chưa thực hiện,Lãi/Lỗ từ hoạt động đầu tư,Thu nhập lãi,Lưu chuyển tiền thuần từ HĐKD trước thay đổi VLĐ,Tăng/Giảm các khoản phải thu,Tăng/Giảm hàng tồn kho,Tăng/Giảm các khoản phải trả,Tăng/Giảm chi phí trả trước,Chi phí lãi vay đã trả,Tiền thu nhập doanh nghiệp đã trả,Tiền thu khác từ các hoạt động kinh doanh,Tiền chi khác từ các hoạt động kinh doanh,Lưu chuyển tiền tệ ròng từ các hoạt động SXKD,Mua sắm TSCĐ,Tiền thu được từ thanh lý tài sản cố định,"Tiền chi cho vay, mua công cụ nợ của đơn vị khác (đồng)","Tiền thu hồi cho vay, bán lại các công cụ nợ của đơn vị khác (đồng)",Đầu tư vào các doanh nghiệp khác,Tiền thu từ việc bán các khoản đầu tư vào doanh nghiệp khác,Tiền thu cổ tức và lợi nhuận được chia,Lưu chuyển từ hoạt động đầu tư,Tăng vốn cổ phần từ góp vốn và/hoặc phát hành cổ phiếu,"Chi trả cho việc mua lại, trả cổ phiếu",Tiền thu được các khoản đi vay,Tiền trả các khoản đi vay,Cổ tức đã trả,Lưu chuyển tiền từ hoạt động tài chính,Lưu chuyển tiền thuần trong kỳ,Tiền và tương đương tiền,Ảnh hưởng của chênh lệch tỷ giá,Tiền và tương đương tiền cuối kỳ
0,NVL,2025,2990720414922,1043689539722,91493039692,664596042667,-2061432382977,147219470559,2876286124585,832102564838,-99268117449,-6258411394143,-270836654187,-2636837475011,-388817886927,0,0,-5945782838294,-23793897176,21464250533,-11717380004537,3516981484332,-5272298106094,12676486129991,1065147826178,266607683227,487268022500,-49031866005,21248207757913,-16219545865752,-197028,5466897851628,-212277303439,4607601921683,-3648406,4395320969838
1,NVL,2024,-2555664274349,1553032140045,340901656636,906763500173,-724297919592,293164269671,-186100627416,11428809770160,-2135609451531,-12814210755554,2516656785,-1697582324023,-569001384074,0,0,-5971178115653,-5666666667,7804735388,-2926542452962,2929427678158,-3700000000,2893613355323,1315166727468,4210103376708,0,-413083000,6089223623609,-3132621801283,-33759401,2956154979925,1195080240980,3412524436724,-2756021,4607601921683
2,NVL,2023,1998881691550,1106459385516,220560611591,552276871342,-1258547070257,357075251918,2976706741660,11750687223303,-1747003638563,-15994763032194,-104770211896,-4091267220638,-416079525176,0,0,-7626489663504,-12766370275,89781296895,-4172394695598,2241815981295,0,8189384151475,812736145102,7148556508894,0,-15000000,4876386461232,-9586061924937,-25239053,-4709715702758,-5187648857368,8600170523502,2770590,3412524436724
3,NVL,2022,3982066348032,-227164114697,115850774058,492288608560,-2616317564495,954042877413,2700766928871,-19468239583927,-10443588459744,31799573314208,-768503964840,-6173136680063,-693598124498,0,0,-3046726569993,-293935317230,121806663375,-10297351483906,14069334968793,-20045623008390,7707960177880,772471687193,-7965336312285,250941290000,0,30149637083585,-28037455868769,-1081850,2363121422966,-8648941459312,17249156145556,-44162742,8600170523502
4,NVL,2021,5086223164450,-1267996316672,-6602795872,-183932403922,-1789917676879,588126620130,2425900591235,-15450033326328,-9408262236790,32341078794517,-496519586817,-4490872652256,-1079993994313,0,0,3841297589248,-895880921185,2015439112,-10924035996542,8643793841875,-13595623128728,3103607087438,531509868720,-13134613809310,4591253993600,-196049500000,36023832294304,-25434712885016,-467474000,14983856428888,5690540208826,11558787555672,-171618942,17249156145556
5,NVL,2020,4649022346311,736177431407,5192553925,-27868814565,-6091949021258,578300666760,-151124837420,-14437175827623,-14079277627374,28866405419147,-215741856085,-3153979701397,-314609953451,0,0,-3485504384203,-199370665048,27802740778,-6049173230372,3177225898286,-12825776162226,10670255300571,288396281192,-4910639836819,668326860000,-1508355000,30262787111740,-17390409779888,-49516473359,13489679363493,5093535142471,6466219516377,-967103176,11558787555672
6,NVL,2019,4272235676472,-2750422518755,152077733090,4193535205,-974173763255,1186691999092,1890602661849,1262582829809,2487766869299,937271650485,119120886872,-2649633213153,-971247780944,0,0,3076463904217,-383243115853,11199068191,-1109336844946,460664701169,-14398343074655,1716435250550,296593687515,-13406030328029,205939730000,-82000000,20460412729964,-16150195525803,-19719873178,4496355060983,-5833211362829,12315170763611,-15739884405,6466219516377
7,NVL,2018,4685614310237,496873282783,10321013452,137534095002,-2465359610460,1443733040227,4308716131241,2737020422473,170559217745,-4266634953316,65351414972,-1793232461571,-647084574232,0,0,574695197312,-170397994908,44855532242,-699653602882,2997627188115,-9232241493214,834105774717,364583371093,-5861121224837,3644346535626,-50046482000,22153049489009,-14771863168477,-12908761912,10962577612246,5676151584721,6638739520534,279658356,12315170763611
8,NVL,2017,2588499024119,484833728737,-5689095922,-5083914401,-1464413967698,1251160373101,2849306147936,1919050031993,-1963235562101,619226427403,-118688935374,-1104335516660,-652457047620,0,0,1548865545577,-1129651141626,8353511141,-1466446465713,4918484078283,-6367994960329,1793455062483,486615118973,-1757184796788,286871900000,-405000000000,17207325658255,-13499500855745,-68165097000,3521531605510,3313212354299,3336969432791,-20792349,6650160994741
9,NVL,2016,2189703612855,226331076287,-41356813092,34551090149,-2228127795722,910387721293,1091488891770,3960297279419,93805533648,-3561263899138,-99019085556,-849017262276,-431733905624,0,0,204557552243,-215251612635,15646566319,-7672922664879,6258296050163,-7218477119177,2048210045846,180791013185,-6603707721178,3985340870000,0,12884785455043,-10939826576518,-54639219932,5875660528593,-523489640342,3859710163282,748909851,3336969432791
10,NVL,2015,608112963781,88779916220,51972653196,21879821943,-331279777789,351425428041,790891005392,-4625495394936,259472715894,1953335836895,-120603156057,-519785506480,-47093302287,0,-128200000,-2309406001579,-33647160381,9187362668,-6399955276371,6462652418650,-3288764833329,0,300231743455,-2950295745308,2034337610000,0,7020343547596,-2714683880779,0,6339997276817,1080295529930,2779414633352,0,3859710163282
11,NVL,2014,130308673878,14834391109,5619762306,10441515618,-59798012145,134768642888,236174973654,-1139332768856,-1803999910006,5502600882532,-79671047706,-509351630239,-28165756837,904654767203,-930272801796,2152636707949,-61503102781,2209090909,-956994281158,344477539449,-424884060000,300000,37684820584,-1059009692997,1694529485600,0,1666623272204,-1924345654392,0,1436807103412,2530434118364,248980514988,0,2779414633352
12,NVL,2013,16997905549,14800833747,2821872916,11126255475,-19958084489,194282057122,220070840320,-322420570232,691294734970,-9121553522,-6580145382,-367304671459,-21124840485,155960832000,-112415847202,228358779008,-11234001396,474300000,-504390569724,576164335135,-1200000000,50784026463,48522331696,159120422174,0,-988170000,564869811283,-978266852234,0,-414385210951,-26906009769,275990740231,-104215474,248980514988

   Meta          Chỉ tiêu cơ cấu nguồn vốn                           \
     CP   Năm Kỳ          (Vay NH+DH)/VCSH   Nợ/VCSH TSCĐ / Vốn CSH
0   NVL  2025  5                  1.747885  3.244541       0.032294
1   NVL  2024  5                  1.821773  4.027973       0.040974
2   NVL  2023  5                  1.864945  4.330490       0.053007
3   NVL  2022  5                  2.243206  4.750735       0.087844
4   NVL  2021  5                  2.476110  3.902072       0.035016
5   NVL  2020  5                  2.607358  3.526358       0.038157
6   NVL  2019  5                  2.482962  2.678467       0.034342
7   NVL  2018  5                  2.211878  2.461333       0.037850
8   NVL  2017  5                  2.123551  2.731556       0.024638
9   NVL  2016  5                  2.131083  2.635660       0.014813
10  NVL  2015  5                  2.210641  3.359228       0.014404
11  NVL  2014  5                  1.691243  3.786454       0.020533
12  NVL  2013  5                  7.034459  8.410917       0.139888

                       Chỉ tiêu hiệu quả hoạt động                 \
   Vốn CSH/Vốn điều lệ           Vòng quay tài sản Vòng quay TSCĐ
0             2.636638                    0.028572       3.629479
1             2.118756                    0.037864       4.182173
2             2.029681                    0.019057       1.500990
3             2.007946                    0.048455       4.140125
4             1.844658                    0.086051      11.204369
5             1.430640                    0.042866       4.883548
6             1.095917                    0.137409      13.698875
7             0.894697                    0.257870      28.250981
8             0.593919                    0.270538      48.933686
9             0.450126                    0.233264      62.203665
10            0.273081                    0.312836      85.103540
11            0.150641                    0.224851      29.196142
12            0.039359                    0.181291      13.022829

                                                         \
   Số ngày thu tiền bình quân Số ngày tồn kho bình quân
0                  164.281225              22160.967374
1                  119.066169               5808.544213
2                  228.244872              14561.661193
3                   86.957978               6499.419062
4                   44.308930               4101.379214
5                   84.573606               8233.688682
6                   30.648635               2072.420421
7                   13.723074               1049.484106
8                   11.357903                935.462689
9                   18.702264                726.598722
10                  28.504981                525.619050
11                  55.234703               1098.222823
12                  51.676035               1665.565917

                                                                      \
   Số ngày thanh toán bình quân   Chu kỳ tiền Vòng quay hàng tồn kho
0                   1218.210018  23543.458617               0.016470
1                    372.398819   6300.009201               0.062838
2                   1084.888287  15874.794352               0.025066
3                    408.893946   6995.270986               0.056159
4                    159.799879   4305.488023               0.088994
5                    305.254950   8623.517238               0.044330
6                    118.769909   2221.838965               0.176123
7                     93.056934   1156.264115               0.347790
8                     90.515891   1037.336483               0.390181
9                     73.568042    818.869028               0.502341
10                    42.333842    596.457873               0.694419
11                    38.306615   1191.764141               0.332355
12                    21.046978   1738.288929               0.219145

   Chỉ tiêu khả năng sinh lợi                                                 \
                Biên EBIT (%) Biên lợi nhuận gộp (%) Biên lợi nhuận ròng (%)
0                    0.372479               0.644314                0.244102
1                   -0.209441               0.009211               -0.711398
2                   -0.096700               0.277956                0.127305
3                    0.157635               0.381839                0.194182
4                    0.236123               0.411709                0.216382
5                    0.075338               0.364653                0.779704
6                    0.151823               0.288323                0.313918
7                    0.261993               0.337337                0.211826
8                    0.199646               0.279981                0.174813
9                    0.105446               0.215116                0.226259
10                   0.111056               0.200776                0.062250
11                   0.087041               0.169666                0.033441
12                   0.128746               0.200294                0.004557

                                                                  \
     ROE (%)  ROIC (%)   ROA (%) EBITDA (Tỷ đồng) EBIT (Tỷ đồng)
0   0.040906  0.020584  0.006974    3638132150777  2594442611055
1  -0.170130 -0.017457 -0.026936    -347303262300 -1900335402345
2   0.016044 -0.004465  0.002426     646465888848  -459993496668
3   0.059663  0.016001  0.009409    1527983165054  1755147279751
4   0.088220  0.034604  0.018620    2250894444704  3518890761376
5   0.138991  0.004685  0.033423    1114852060293   378674628886
6   0.154462  0.028104  0.043135   -1090852839015  1659569679740
7   0.194959  0.083670  0.054624    4502817980388  4005944697605
8   0.174523  0.074419  0.047294    2807178532221  2322344803484
9   0.206302  0.032951  0.052778    1002324620538   775993544251
10  0.087850  0.052603  0.019474     829903975631   741124059411
11  0.044187  0.034697  0.007519     258705605372   243871214263
12  0.008301  0.042998  0.000826     220845896500   206045062753

          Chỉ tiêu thanh khoản                             \
   Chỉ số thanh toán hiện thời Chỉ số thanh toán tiền mặt
0                     2.160850                   0.045829
1                     1.938319                   0.042972
2                     2.190066                   0.039097
3                     2.534274                   0.110013
4                     3.170766                   0.350487
5                     3.633892                   0.367794
6                     3.785019                   0.343772
7                     1.788918                   0.439904
8                     1.816824                   0.293499
9                     2.017739                   0.222298
10                    1.357829                   0.289017
11                    1.448909                   0.280571
12                    1.536504                   0.080635

                                                                       \
   Chỉ số thanh toán nhanh Khả năng chi trả lãi vay Đòn bẩy tài chính
0                 0.539223               -17.622958          4.244541
1                 0.554185                 6.521470          5.027973
2                 0.577704                 1.403675          5.330490
3                 0.779616                -2.078795          5.750735
4                 0.887104                -6.841893          4.902072
5                 0.806838                -0.668883          4.526358
6                 0.657125                -1.448634          3.678467
7                 0.640708                -2.895854          3.461333
8                 0.558223                -1.926637          3.731556
9                 0.864201                -0.899105          3.635660
10                0.742713                -2.108908          4.359228
11                0.597077                -1.809555          4.786454
12                0.342303                -1.060546         10.048671

   Chỉ tiêu định giá                                                    \
   Vốn hóa (Tỷ đồng) Số CP lưu hành (Triệu CP)          P/E        P/B
0     25110208676250                2232018549    14.768466   0.554362
1     26033895582300                1950104538    -4.033274   0.688113
2     19988571514500                1950104538    33.007415   0.525367
3     33249282372900                1950104538    15.378440   0.888035
4     27025898466000                1930421319     8.380937   0.771398
5     89751962027000                 986285297    22.901332   3.467397
6     98893161294000                 969540797    28.819800   4.438965
7     95602220748000                 937276674    29.517077   5.034795
8     66265196376000                 649658788    32.587061   5.254707
9     60812321868000                 596199234    36.522216   6.691152
10    37566167622000                 368295761    90.428787   7.342984
11    23460000000000                 230000000   250.383886   8.797303
12    12240000000000                 120000000  1678.453754  13.932829


          P/S P/Cash Flow    EPS (VND)    BVPS (VND)   EV/EBITDA
0    3.605019   -4.223196   761.758211  20293.594124   24.162305
1    2.869262   -4.359926 -3309.966096  19400.891239 -238.961615
2    4.202014   -2.620940   310.536286  19510.161703  114.914730
3    2.986222  -10.913117  1108.695037  19199.700471   58.585730
4    1.813483    7.035617  1670.457633  18148.868557   31.229874
5   17.856260  -25.750064  3973.567938  26244.469391  114.001229
6    9.047051   32.145074  3539.233391  22978.328030 -116.438460
7    6.252485  166.352914  3455.626704  20259.017660   24.694564
8    5.696637   42.783053  3130.076662  19411.169563   27.630871
9    8.263463  297.287102  2792.820692  15244.012568   70.814000
10   5.629210  -16.266593  1127.959396  13890.811502   50.247003
11   8.373157   10.898263   407.374458  11594.462332   94.109968
12   7.648100   53.599866    60.770218   7320.839379   74.553158

In [ ]:
# Tổng hợp Lợi nhuận thuần theo năm từ dữ liệu quý
pre_audit = stock_data.finance.income_statement(period="quarter", lang="vi", dropna=True)
pre_audit_sum = pre_audit.groupby(['CP', 'Năm'])['Lợi nhuận thuần'].sum().reset_index()
pre_audit_sum.rename(columns={'Lợi nhuận thuần': 'Lợi nhuận thuần (trước kiểm toán)'}, inplace=True)

# Dữ liệu năm (sau kiểm toán)
post_audit = stock_data.finance.income_statement(period="year", lang="vi", dropna=True)
post_audit = post_audit[['CP', 'Năm', 'Lợi nhuận thuần']].rename(
    columns={'Lợi nhuận thuần': 'Lợi nhuận thuần (sau kiểm toán)'}
)

# Gộp và tính chênh lệch
result = pre_audit_sum.merge(post_audit, on=['CP', 'Năm'])
result['Chênh lệch'] = result['Lợi nhuận thuần (sau kiểm toán)'] - result['Lợi nhuận thuần (trước kiểm toán)']
result['Phần trăm chênh lệch'] = (result['Chênh lệch'] / result['Lợi nhuận thuần (trước kiểm toán)']) * 100

# Thêm cột Fraud: nếu phần trăm chênh lệch > 5% => 1, ngược lại 0
result['Fraud'] = (result['Phần trăm chênh lệch'].abs() > 5).astype(int)

import pandas as pd
pd.set_option("display.max_columns", None)
display(result)

,CP,Năm,Lợi nhuận thuần (trước kiểm toán),Lợi nhuận thuần (sau kiểm toán),Chênh lệch,Phần trăm chênh lệch,Fraud
0,NVL,2015,531261553736,441759950527,-89501603209,-16.846994,1
1,NVL,2016,1500272858439,1659349312978,159076454539,10.603168,1
2,NVL,2017,2061643232256,2061643232256,0,0.000000,0
3,NVL,2018,3267229378575,3278949287486,11719908911,0.358711,0
4,NVL,2019,3378493933205,3387422101911,8928168706,0.264265,0
5,NVL,2020,3883809820111,3906501579676,22691759565,0.584265,0
6,NVL,2021,3460318062895,3454752838912,-5565223983,-0.160830,0
7,NVL,2022,2181530210596,2181530210596,0,0.000000,0
8,NVL,2023,684791338424,485864524898,-198926813526,-29.049260,1
9,NVL,2024,-4394642203703,-4394642203703,0,-0.000000,0
10,NVL,2025,1818671096338,1818671096338,0,0.000000,0

In [ ]:
import pandas as pd

df = pd.read_excel("all_symbols.xlsx")

finance_keywords = ["ngân hàng","chứng khoán","bảo hiểm","tài chính","quỹ"]
pattern = "|".join(finance_keywords)

non_financial = df[~df["organ_name"].str.lower().str.contains(pattern, na=False)]

symbols_500 = non_financial["symbol"].head(500)

print(symbols_500.tolist())

['VGI', 'VKP', 'DMS', 'AGM', 'BKC', 'VGS', 'POB', 'VNG', 'PVL', 'ACE', 'IDC', 'VLG', 'TRV', 'PVO', 'GTD', 'NTT', 'BSD', 'IJC', 'KOS', 'CCM', 'THT', 'MGC', 'VMT', 'MHC', 'VTD', 'LMH', 'TNM', 'SBT', 'LLM', 'TMW', 'NBW', 'HPO', 'KSQ', 'HSV', 'BTU', 'VXT', 'PXT', 'ANV', 'TNV', 'CST', 'TAW', 'NT2', 'MWG', 'CFV', 'HWS', 'SSN', 'TNA', 'TNG', 'SJM', 'GEX', 'FOX', 'MDA', 'HDW', 'IDP', 'EME', 'DTE', 'PEQ', 'IRC', 'CAD', 'VNL', 'KHP', 'PVV', 'PSH', 'PTP', 'VKC', 'HTN', 'IME', 'TCL', 'VIC', 'REE', 'TUG', 'TNT', 'BCC', 'KDM', 'FDC', 'LEC', 'SCC', 'GTT', 'HLB', 'DST', 'PTT', 'CCP', 'VCM', 'VCX', 'DCS', 'BT1', 'CDC', 'C92', 'LKW', 'HBH', 'TDP', 'VFR', 'TLT', 'CTF', 'HPT', 'PHH', 'CNA', 'HLC', 'DOC', 'VLB', 'PVC', 'VHM', 'PTV', 'SAM', 'HSI', 'SPV', 'VTH', 'VE9', 'KCB', 'TTB', 'QCC', 'PMJ', 'DTA', 'TBD', 'TSB', 'NLS', 'CII', 'TMT', 'HAN', 'DDM', 'SGH', 'NET', 'L45', 'TOT', 'RCD', 'VC5', 'DNA', 'RAL', 'VSC', 'CC1', 'SDN', 'SP2', 'PMG', 'DSD', 'CCV', 'PXL', 'MFS', 'OIL', 'HAS', 'TVT', 'PSD', 'SHE', 'DSH', 'X77', 'VMS', 'CDG', 'HTC', 'NAG', 'PTE', 'POV', 'HD2', 'SKN', 'DTD', 'CPH', 'SD3', 'TBC', 'DAE', 'DHT', 'CAT', 'HID', 'HPM', 'GCB', 'V12', 'PTD', 'CHP', 'SIV', 'DWC', 'UDL', 'TID', 'VHC', 'DMC', 'PSG', 'VC6', 'XLV', 'BHP', 'DHN', 'MTS', 'TV2', 'MCH', 'EIC', 'FSO', 'VTP', 'TTE', 'DHA', 'BLN', 'MTP', 'CCL', 'ODE', 'FBC', 'EBS', 'GER', 'TIP', 'TIX', 'BMK', 'SHA', 'SZE', 'SHG', 'VNC', 'BTS', 'FRM', 'NHA', 'STD', 'ANT', 'BHA', 'VIM', 'ABC', 'PGD', 'VE2', 'VTI', 'S72', 'LSG', 'CCT', 'PSW', 'HNA', 'DNP', 'BNW', 'CAP', 'UIC', 'LTG', 'DVN', 'ND2', 'PTG', 'TCK', 'DTI', 'PDC', 'NDN', 'BMV', 'SII', 'SVC', 'CIA', 'CSC', 'VGV', 'TCM', 'VPD', 'BNA', 'HMG', 'LTC', 'CDR', 'A32', 'L61', 'VWS', 'CH5', 'BMI', 'VES', 'HGM', 'HDG', 'TNB', 'GLC', 'KSV', 'MQB', 'UPC', 'TGP', 'HMR', 'D2D', 'VSA', 'DCH', 'HFC', 'VIW', 'CRC', 'EVG', 'VSH', 'NTB', 'AME', 'ISG', 'L63', 'PIT', 'ECI', 'MST', 'GTS', 'TVD', 'GMC', 'PVE', 'UMC', 'HVT', 'THB', 'VMG', 'CKD', 'BQP', 'ABS', 'MML', 'THM', 'SJS', 'BSH', 'HAR', 'ITQ', 'TV4', 'VTE', 'PND', 'NTF', 'VHD', 'DVT', 'CJC', 'VPH', 'CLL', 'GMA', 'VDT', 'SD8', 'TV6', 'VQC', 'GND', 'BFC', 'TRA', 'TDW', 'ICF', 'PET', 'NHT', 'FCM', 'VIP', 'THS', 'TDB', 'SZL', 'TDG', 'VRC', 'TDF', 'CYC', 'C69', 'PVI', 'DKC', 'UDC', 'CLH', 'MVB', 'HHS', 'FT1', 'BHG', 'SMA', 'G20', 'DP2', 'VID', 'NFC', 'MTL', 'PIA', 'VFC', 'FRC', 'PCC', 'CNT', 'SJD', 'BHK', 'M10', 'S55', 'GEL', 'DP1', 'NLG', 'L43', 'HAF', 'PQN', 'C47', 'SID', 'PC1', 'POS', 'PSN', 'VBG', 'NBP', 'CCR', 'BAF', 'HMC', 'BBH', 'GVT', 'NWT', 'PMW', 'BMD', 'DC1', 'SCL', 'F88', 'AMP', 'MBG', 'VGC', 'MBT', 'GMD', 'VIF', 'EGL', 'VFG', 'VTM', 'GDA', 'PHN', 'PSC', 'TLD', 'SDT', 'SDA', 'HAT', 'IST', 'BVG', 'SD2', 'HU3', 'VC2', 'HTM', 'BRS', 'VGL', 'VHL', 'PNP', 'NBE', 'PNT', 'KTL', 'TLH', 'VCE', 'SRC', 'TIE', 'SCD', 'C21', 'SIG', 'TBR', 'L10', 'VDB', 'SLD', 'FCS', 'QBS', 'CMP', 'VC3', 'ICT', 'BHH', 'PGN', 'SBR', 'MQN', 'HT1', 'LSS', 'PHP', 'HJC', 'VLC', 'DAG', 'CPI', 'TRS', 'PLX', 'SHI', 'SBL', 'DFC', 'BWS', 'TDC', 'PSE', 'MA1', 'VDL', 'QNC', 'ALC', 'TSD', 'DSP', 'SGR', 'CIG', 'MKP', 'ONW', 'ILS', 'SFG', 'DXS', 'DNL', 'CEO', 'PPS', 'HNP', 'VTO', 'DPC', 'SHN', 'TQN', 'LQN', 'VCS', 'HSP', 'STS', 'VBC', 'ELC', 'HSL', 'HCT', 'TRC', 'MSH', 'GDT', 'SDK', 'CCA', 'G36', 'HAV', 'MTA', 'VNI', 'NAV', 'LM8', 'DNT', 'VNP', 'CRV', 'SSG', 'DAH', 'DVM', 'SPC', 'SBB', 'MCG', 'SDU', 'VGR', 'HOM', 'AGP', 'MCF', 'VGG', 'PJT', 'SBV', 'BSQ', 'MAC', 'DLD', 'TMP', 'BTT', 'PVH', 'CTT', 'VE1', 'VTG', 'HTG', 'DBD', 'LO5', 'GCF', 'TMG', 'TKC', 'TAR']

In [ ]:
import time
import numpy as np
import pandas as pd
from vnstock import Vnstock

symbols = ['VGI', 'VKP', 'DMS', 'AGM', 'BKC', 'VGS', 'POB', 'VNG', 'PVL', 'ACE', 'IDC', 'VLG', 'TRV', 'PVO', 'GTD', 'NTT', 'BSD', 'IJC', 'KOS', 'CCM', 'THT', 'MGC', 'VMT', 'MHC', 'VTD', 'LMH', 'TNM', 'SBT', 'LLM', 'TMW', 'NBW', 'HPO', 'KSQ', 'HSV', 'BTU', 'VXT', 'PXT', 'ANV', 'TNV', 'CST', 'TAW', 'NT2', 'MWG', 'CFV', 'HWS', 'SSN', 'TNA', 'TNG', 'SJM', 'GEX', 'FOX', 'MDA', 'HDW', 'IDP', 'EME', 'DTE', 'PEQ', 'IRC', 'CAD', 'VNL', 'KHP', 'PVV', 'PSH', 'PTP', 'VKC', 'HTN', 'IME', 'TCL', 'VIC', 'REE', 'TUG', 'TNT', 'BCC', 'KDM', 'FDC', 'LEC', 'SCC', 'GTT', 'HLB', 'DST', 'PTT', 'CCP', 'VCM', 'VCX', 'DCS', 'BT1', 'CDC', 'C92', 'LKW', 'HBH', 'TDP', 'VFR', 'TLT', 'CTF', 'HPT', 'PHH', 'CNA', 'HLC', 'DOC', 'VLB', 'PVC', 'VHM', 'PTV', 'SAM', 'HSI', 'SPV', 'VTH', 'VE9', 'KCB', 'TTB', 'QCC', 'PMJ', 'DTA', 'TBD', 'TSB', 'NLS', 'CII', 'TMT', 'HAN', 'DDM', 'SGH', 'NET', 'L45', 'TOT', 'RCD', 'VC5', 'DNA', 'RAL', 'VSC', 'CC1', 'SDN', 'SP2', 'PMG', 'DSD', 'CCV', 'PXL', 'MFS', 'OIL', 'HAS', 'TVT', 'PSD', 'SHE', 'DSH', 'X77', 'VMS', 'CDG', 'HTC', 'NAG', 'PTE', 'POV', 'HD2', 'SKN', 'DTD', 'CPH', 'SD3', 'TBC', 'DAE', 'DHT', 'CAT', 'HID', 'HPM', 'GCB', 'V12', 'PTD', 'CHP', 'SIV', 'DWC', 'UDL', 'TID', 'VHC', 'DMC', 'PSG', 'VC6', 'XLV', 'BHP', 'DHN', 'MTS', 'TV2', 'MCH', 'EIC', 'FSO', 'VTP', 'TTE', 'DHA', 'BLN', 'MTP', 'CCL', 'ODE', 'FBC', 'EBS', 'GER', 'TIP', 'TIX', 'BMK', 'SHA', 'SZE', 'SHG', 'VNC', 'BTS', 'FRM', 'NHA', 'STD', 'ANT', 'BHA', 'VIM', 'ABC', 'PGD', 'VE2', 'VTI', 'S72', 'LSG', 'CCT', 'PSW', 'HNA', 'DNP', 'BNW', 'CAP', 'UIC', 'LTG', 'DVN', 'ND2', 'PTG', 'TCK', 'DTI', 'PDC', 'NDN', 'BMV', 'SII', 'SVC', 'CIA', 'CSC', 'VGV', 'TCM', 'VPD', 'BNA', 'HMG', 'LTC', 'CDR', 'A32', 'L61', 'VWS', 'CH5', 'BMI', 'VES', 'HGM', 'HDG', 'TNB', 'GLC', 'KSV', 'MQB', 'UPC', 'TGP', 'HMR', 'D2D', 'VSA', 'DCH', 'HFC', 'VIW', 'CRC', 'EVG', 'VSH', 'NTB', 'AME', 'ISG', 'L63', 'PIT', 'ECI', 'MST', 'GTS', 'TVD', 'GMC', 'PVE', 'UMC', 'HVT', 'THB', 'VMG', 'CKD', 'BQP', 'ABS', 'MML', 'THM', 'SJS', 'BSH', 'HAR', 'ITQ', 'TV4', 'VTE', 'PND', 'NTF', 'VHD', 'DVT', 'CJC', 'VPH', 'CLL', 'GMA', 'VDT', 'SD8', 'TV6', 'VQC', 'GND', 'BFC', 'TRA', 'TDW', 'ICF', 'PET', 'NHT', 'FCM', 'VIP', 'THS', 'TDB', 'SZL', 'TDG', 'VRC', 'TDF', 'CYC', 'C69', 'PVI', 'DKC', 'UDC', 'CLH', 'MVB', 'HHS', 'FT1', 'BHG', 'SMA', 'G20', 'DP2', 'VID', 'NFC', 'MTL', 'PIA', 'VFC', 'FRC', 'PCC', 'CNT', 'SJD', 'BHK', 'M10', 'S55', 'GEL', 'DP1', 'NLG', 'L43', 'HAF', 'PQN', 'C47', 'SID', 'PC1', 'POS', 'PSN', 'VBG', 'NBP', 'CCR', 'BAF', 'HMC', 'BBH', 'GVT', 'NWT', 'PMW', 'BMD', 'DC1', 'SCL', 'F88', 'AMP', 'MBG', 'VGC', 'MBT', 'GMD', 'VIF', 'EGL', 'VFG', 'VTM', 'GDA', 'PHN', 'PSC', 'TLD', 'SDT', 'SDA', 'HAT', 'IST', 'BVG', 'SD2', 'HU3', 'VC2', 'HTM', 'BRS', 'VGL', 'VHL', 'PNP', 'NBE', 'PNT', 'KTL', 'TLH', 'VCE', 'SRC', 'TIE', 'SCD', 'C21', 'SIG', 'TBR', 'L10', 'VDB', 'SLD', 'FCS', 'QBS', 'CMP', 'VC3', 'ICT', 'BHH', 'PGN', 'SBR', 'MQN', 'HT1', 'LSS', 'PHP', 'HJC', 'VLC', 'DAG', 'CPI', 'TRS', 'PLX', 'SHI', 'SBL', 'DFC', 'BWS', 'TDC', 'PSE', 'MA1', 'VDL', 'QNC', 'ALC', 'TSD', 'DSP', 'SGR', 'CIG', 'MKP', 'ONW', 'ILS', 'SFG', 'DXS', 'DNL', 'CEO', 'PPS', 'HNP', 'VTO', 'DPC', 'SHN', 'TQN', 'LQN', 'VCS', 'HSP', 'STS', 'VBC', 'ELC', 'HSL', 'HCT', 'TRC', 'MSH', 'GDT', 'SDK', 'CCA', 'G36', 'HAV', 'MTA', 'VNI', 'NAV', 'LM8', 'DNT', 'VNP', 'CRV', 'SSG', 'DAH', 'DVM', 'SPC', 'SBB', 'MCG', 'SDU', 'VGR', 'HOM', 'AGP', 'MCF', 'VGG', 'PJT', 'SBV', 'BSQ', 'MAC', 'DLD', 'TMP', 'BTT', 'PVH', 'CTT', 'VE1', 'VTG', 'HTG', 'DBD', 'LO5', 'GCF', 'TMG', 'TKC', 'TAR']

def process_stock(symbol: str) -> pd.DataFrame | None:
    try:
        stock = Vnstock().stock(symbol=symbol, source="VCI")

        # Dữ liệu năm
        bs = stock.finance.balance_sheet(period="year", lang="vi", dropna=True).copy()
        is_ = stock.finance.income_statement(period="year", lang="vi", dropna=True).copy()
        cf = stock.finance.cash_flow(period="year", dropna=True).copy()

        # Dữ liệu quý: bắt buộc phải có để tính Fraud
        is_quarter = stock.finance.income_statement(period="quarter", lang="vi", dropna=True).copy()

        def normalize_keys(df, fallback=symbol):
            d = df.copy().reset_index()
            cols = list(d.columns)
            low = {str(c).strip().lower(): c for c in cols}

            cp_col = next((low[k] for k in ["cp","ticker","symbol","mã","ma","code"] if k in low), None)
            year_col = next((low[k] for k in [
                "năm","nam","year","fiscalyear","reportyear","yearreport",
                "year_report","yearreporting","yearreported"
            ] if k in low), None)

            if cp_col is None:
                d["CP"] = fallback
            else:
                d = d.rename(columns={cp_col: "CP"})

            if year_col is None:
                raise KeyError(f"Không tìm thấy cột Năm/year. Columns: {cols}")
            else:
                d = d.rename(columns={year_col: "Năm"})

            d["CP"] = d["CP"].astype(str).str.upper()
            d["Năm"] = pd.to_numeric(d["Năm"], errors="coerce").astype("Int64")
            return d

        bs = normalize_keys(bs)
        is_ = normalize_keys(is_)
        cf = normalize_keys(cf)
        is_quarter = normalize_keys(is_quarter)

        # Fraud bắt buộc: phải có đủ các cột cần thiết
        if is_quarter.empty or "Kỳ" not in is_quarter.columns or "Lợi nhuận thuần" not in is_quarter.columns:
            print(f"SKIP {symbol}: thiếu dữ liệu quý để tính Fraud")
            return None

        if "Lợi nhuận thuần" not in is_.columns:
            print(f"SKIP {symbol}: thiếu dữ liệu năm để tính Fraud")
            return None

        quarters = (
            is_quarter.pivot_table(
                index=["CP", "Năm"],
                columns="Kỳ",
                values="Lợi nhuận thuần",
                aggfunc="sum"
            )
            .reset_index()
            .rename(columns={1: "Q1", 2: "Q2", 3: "Q3", 4: "Q4"})
        )

        # đủ 4 quý mới tính Fraud
        for q in ["Q1", "Q2", "Q3", "Q4"]:
            if q not in quarters.columns:
                quarters[q] = np.nan

        # chỉ giữ năm có đủ 4 quý
        quarters = quarters.dropna(subset=["Q1", "Q2", "Q3", "Q4"], how="any").copy()
        if quarters.empty:
            print(f"SKIP {symbol}: không có năm nào đủ 4 quý")
            return None

        quarters["Lợi nhuận thuần (trước kiểm toán)"] = quarters[["Q1", "Q2", "Q3", "Q4"]].sum(axis=1)

        year_df = is_[["CP", "Năm", "Lợi nhuận thuần"]].rename(
            columns={"Lợi nhuận thuần": "Lợi nhuận thuần (sau kiểm toán)"}
        )

        profit_df = quarters.merge(year_df, on=["CP", "Năm"], how="inner")
        if profit_df.empty:
            print(f"SKIP {symbol}: không match được dữ liệu quý và năm")
            return None

        profit_df["Chênh lệch"] = (
            profit_df["Lợi nhuận thuần (sau kiểm toán)"] -
            profit_df["Lợi nhuận thuần (trước kiểm toán)"]
        )

        profit_df["Phần trăm chênh lệch"] = np.where(
            profit_df["Lợi nhuận thuần (trước kiểm toán)"] == 0,
            np.nan,
            profit_df["Chênh lệch"] / profit_df["Lợi nhuận thuần (trước kiểm toán)"] * 100
        )

        profit_df = profit_df.dropna(subset=["Phần trăm chênh lệch"]).copy()
        if profit_df.empty:
            print(f"SKIP {symbol}: không tính được phần trăm chênh lệch")
            return None

        profit_df["Fraud"] = (profit_df["Phần trăm chênh lệch"].abs() > 5).astype(int)

        # Merge dữ liệu
        df = (
            bs.merge(is_, on=["CP", "Năm"], how="outer", suffixes=("", "_is"))
              .merge(cf, on=["CP", "Năm"], how="outer", suffixes=("", "_cf"))
              .merge(profit_df[["CP", "Năm", "Fraud"]], on=["CP", "Năm"], how="inner")
              .sort_values(["CP", "Năm"])
              .reset_index(drop=True)
        )

        def pick_col(d, candidates, required=True):
            for c in candidates:
                if c in d.columns:
                    return c
            if required:
                raise KeyError(f"Thiếu cột. Cần một trong {candidates}")
            return None

        def get_series(d, candidates, default=np.nan):
            col = pick_col(d, candidates, required=False)
            if col is None:
                return pd.Series(default, index=d.index, dtype="float64")
            return pd.to_numeric(d[col], errors="coerce")

        def safe_div(a, b):
            a = pd.to_numeric(a, errors="coerce")
            b = pd.to_numeric(b, errors="coerce")
            return np.where((b == 0) | pd.isna(b), np.nan, a / b)

        def lag(x):
            return x.groupby(df["CP"]).shift(1)

        TA   = pd.to_numeric(df[pick_col(df, ["TỔNG CỘNG TÀI SẢN (đồng)"])], errors="coerce")
        CA   = pd.to_numeric(df[pick_col(df, ["TÀI SẢN NGẮN HẠN (đồng)"])], errors="coerce")
        TL   = pd.to_numeric(df[pick_col(df, ["NỢ PHẢI TRẢ (đồng)"])], errors="coerce")
        EQ   = pd.to_numeric(df[pick_col(df, ["VỐN CHỦ SỞ HỮU (đồng)"])], errors="coerce")
        REV  = pd.to_numeric(df[pick_col(df, ["Doanh thu thuần"])], errors="coerce")
        COGS = pd.to_numeric(df[pick_col(df, ["Giá vốn hàng bán"])], errors="coerce")

        CASH = get_series(df, ["Tiền và tương đương tiền (đồng)"])
        AR   = get_series(df, ["Các khoản phải thu ngắn hạn (đồng)"])
        INV  = get_series(df, ["Hàng tồn kho ròng", "Hàng tồn kho, ròng (đồng)"])
        PPE  = get_series(df, ["Tài sản cố định (đồng)"])
        LTI  = get_series(df, ["Đầu tư dài hạn (đồng)"])
        CL   = get_series(df, ["Nợ ngắn hạn (đồng)"])

        SGA1 = pick_col(df, ["Chi phí bán hàng"], required=False)
        SGA2 = pick_col(df, ["Chi phí quản lý DN"], required=False)
        SGA  = (pd.to_numeric(df[SGA1], errors="coerce") if SGA1 else 0) + \
               (pd.to_numeric(df[SGA2], errors="coerce") if SGA2 else 0)

        ni_col = pick_col(df, ["Lợi nhuận sau thuế của Cổ đông công ty mẹ (đồng)", "Lợi nhuận thuần"], required=False)
        NI = pd.to_numeric(df[ni_col], errors="coerce") if ni_col else pd.Series(np.nan, index=df.index)

        CFO = get_series(df, [
            "Lưu chuyển tiền tệ ròng từ các hoạt động SXKD",
            "Lưu chuyển tiền thuần từ hoạt động kinh doanh",
            "Net cash inflows/outflows from operating activities",
            "Net cash inflows/outflows from operating activities_cf",
            "Net cash from operating activities",
            "Net cash from operating activities_cf",
        ])

        DEP = get_series(df, [
            "Khấu hao TSCĐ",
            "Khấu hao và phân bổ",
            "Depreciation and Amortisation",
            "Depreciation and Amortisation_cf",
            "Depreciation & Amortization",
            "Depreciation & Amortization_cf",
        ])

        STDEBT = get_series(df, ["Vay và nợ thuê tài chính ngắn hạn (đồng)"])
        LTDEBT = get_series(df, ["Vay và nợ thuê tài chính dài hạn (đồng)"])

        df["Firm_Size"] = np.where(TA > 0, np.log(TA), np.nan)
        df["ROA"] = safe_div(NI, TA)
        df["ROE"] = safe_div(NI, EQ)
        df["Net_Profit_Margin"] = safe_div(NI, REV)
        df["Gross_Profit_Margin"] = safe_div(REV - COGS, REV)
        df["Sales_Growth"] = REV.groupby(df["CP"]).pct_change()
        df["Revenue_Growth"] = df["Sales_Growth"]
        df["Debt_to_Assets"] = safe_div(TL, TA)
        df["Debt_to_Equity"] = safe_div(TL, EQ)
        df["Receivables_to_Revenue"] = safe_div(AR, REV)
        df["Receivables_to_Assets"] = safe_div(AR, TA)
        df["Inventory_to_Assets"] = safe_div(INV, TA)
        df["Current_Assets_to_Total_Assets"] = safe_div(CA, TA)
        df["CFO_to_Assets"] = safe_div(CFO, TA)
        df["CFO_to_Revenue"] = safe_div(CFO, REV)
        df["Accruals_to_Assets"] = safe_div(NI - CFO, TA)
        df["TATA"] = df["Accruals_to_Assets"]
        df["Working_Capital_to_Assets"] = safe_div(CA - CL, TA)

        ar_rev = safe_div(AR, REV)
        df["DSRI"] = safe_div(ar_rev, lag(pd.Series(ar_rev, index=df.index)))

        gm = safe_div(REV - COGS, REV)
        df["GMI"] = safe_div(lag(pd.Series(gm, index=df.index)), gm)

        aq = 1 - safe_div(CA + PPE, TA)
        df["AQI"] = safe_div(aq, lag(pd.Series(aq, index=df.index)))

        df["SGI"] = safe_div(REV, lag(pd.Series(REV, index=df.index)))

        dep_rate = safe_div(DEP, PPE + DEP)
        df["DEPI"] = safe_div(lag(pd.Series(dep_rate, index=df.index)), dep_rate)

        sga_rev = safe_div(SGA, REV)
        df["SGAI"] = safe_div(sga_rev, lag(pd.Series(sga_rev, index=df.index)))

        lev = safe_div(TL, TA)
        df["LVGI"] = safe_div(lev, lag(pd.Series(lev, index=df.index)))

        df["Delta_Receivables"] = safe_div(AR - lag(pd.Series(AR, index=df.index)), TA)
        df["Delta_Inventory"] = safe_div(INV - lag(pd.Series(INV, index=df.index)), TA)

        dREV = REV - lag(pd.Series(REV, index=df.index))
        dAR  = AR  - lag(pd.Series(AR, index=df.index))
        df["Delta_Cash_Sales"] = dREV - dAR

        df["Delta_ROA"] = df["ROA"] - lag(df["ROA"])
        df["Soft_Assets"] = safe_div(TA - PPE - CASH, TA)

        WC  = (CA - CASH) - (CL - STDEBT)
        NCO = (TA - CA - LTI) - (TL - CL - LTDEBT)
        FIN = LTI - (LTDEBT + STDEBT)

        dWC  = WC  - lag(pd.Series(WC, index=df.index))
        dNCO = NCO - lag(pd.Series(NCO, index=df.index))
        dFIN = FIN - lag(pd.Series(FIN, index=df.index))

        avgTA = (TA + lag(pd.Series(TA, index=df.index))) / 2
        df["RSST_Accruals"] = safe_div(dWC + dNCO + dFIN, avgTA)

        cols_needed = [
            "CP","Năm","DSRI","GMI","AQI","SGI","DEPI","SGAI","LVGI","TATA",
            "RSST_Accruals","Delta_Receivables","Delta_Inventory","Delta_Cash_Sales","Delta_ROA","Soft_Assets",
            "ROA","ROE","Net_Profit_Margin","Gross_Profit_Margin","Sales_Growth","Revenue_Growth",
            "Debt_to_Assets","Debt_to_Equity","Receivables_to_Revenue","Receivables_to_Assets",
            "Inventory_to_Assets","Current_Assets_to_Total_Assets","CFO_to_Assets","CFO_to_Revenue",
            "Accruals_to_Assets","Working_Capital_to_Assets","Firm_Size","Fraud"
        ]

        df = df[[c for c in cols_needed if c in df.columns]]
        df = df[(df["Năm"] >= 2018) & (df["Năm"] <= 2024)].reset_index(drop=True)

        # Fraud là bắt buộc
        if df.empty or df["Fraud"].isna().all():
            print(f"SKIP {symbol}: không có Fraud hợp lệ")
            return None

        return df

    except Exception as e:
        print(f"Lỗi ở mã {symbol}: {e}")
        return None
    
    
import time
import pandas as pd

all_dfs = []
failed_symbols = []

batch_size = 5   # nhỏ thôi để an toàn

for start in range(0, len(symbols), batch_size):
    batch = symbols[start:start + batch_size]
    print(f"\n=== Batch {start+1} - {start+len(batch)} ===")

    for i, sym in enumerate(batch, start + 1):
        print(f"[{i}/{len(symbols)}] Đang xử lý {sym}...")

        df_sym = process_stock(sym)

        if df_sym is not None and not df_sym.empty:
            all_dfs.append(df_sym)
            print(f"OK: {sym}")
        else:
            failed_symbols.append(sym)
            print(f"SKIP: {sym}")

        time.sleep(8)   # 4 request/mã => ~40 request/phút, an toàn hơn

    if start + batch_size < len(symbols):
        print("Nghỉ 25 giây giữa các batch...")
        time.sleep(25)

all_data = pd.concat(all_dfs, ignore_index=True) if all_dfs else pd.DataFrame()

print("Số dòng:", len(all_data), "| Số cột:", all_data.shape[1])
print("Số mã lỗi/bỏ qua:", len(failed_symbols))
print("Danh sách mã lỗi:", failed_symbols)

display(all_data.head(20))

=== Batch 1 - 5 ===
[1/500] Đang xử lý VGI...
OK: VGI
[2/500] Đang xử lý VKP...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP VKP: không có năm nào đủ 4 quý
SKIP: VKP
[3/500] Đang xử lý DMS...

2026-03-06 12:50:13 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 12:50:13 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 12:50:13 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã DMS: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: DMS
[4/500] Đang xử lý AGM...
OK: AGM
[5/500] Đang xử lý BKC...
OK: BKC
Nghỉ 25 giây giữa các batch...

=== Batch 6 - 10 ===
[6/500] Đang xử lý VGS...
OK: VGS
[7/500] Đang xử lý POB...

2026-03-06 12:51:22 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 12:51:22 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 12:51:22 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã POB: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: POB
[8/500] Đang xử lý VNG...
OK: VNG
[9/500] Đang xử lý PVL...
OK: PVL
[10/500] Đang xử lý ACE...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP ACE: không có năm nào đủ 4 quý
SKIP: ACE
Nghỉ 25 giây giữa các batch...

=== Batch 11 - 15 ===
[11/500] Đang xử lý IDC...
OK: IDC
[12/500] Đang xử lý VLG...
OK: VLG
[13/500] Đang xử lý TRV...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP TRV: không có Fraud hợp lệ
SKIP: TRV
[14/500] Đang xử lý PVO...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP PVO: không có năm nào đủ 4 quý
SKIP: PVO
[15/500] Đang xử lý GTD...

2026-03-06 12:53:10 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 12:53:10 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 12:53:10 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã GTD: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: GTD
Nghỉ 25 giây giữa các batch...

=== Batch 16 - 20 ===
[16/500] Đang xử lý NTT...
OK: NTT
[17/500] Đang xử lý BSD...

2026-03-06 12:53:56 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 12:53:56 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 12:53:56 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã BSD: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: BSD
[18/500] Đang xử lý IJC...
OK: IJC
[19/500] Đang xử lý KOS...
OK: KOS
[20/500] Đang xử lý CCM...
OK: CCM
Nghỉ 25 giây giữa các batch...

=== Batch 21 - 25 ===
[21/500] Đang xử lý THT...
OK: THT
[22/500] Đang xử lý MGC...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP MGC: không có năm nào đủ 4 quý
SKIP: MGC
[23/500] Đang xử lý VMT...

2026-03-06 12:55:24 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 12:55:24 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 12:55:24 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã VMT: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: VMT
[24/500] Đang xử lý MHC...
OK: MHC
[25/500] Đang xử lý VTD...
OK: VTD
Nghỉ 25 giây giữa các batch...

=== Batch 26 - 30 ===
[26/500] Đang xử lý LMH...
OK: LMH
[27/500] Đang xử lý TNM...

2026-03-06 12:56:31 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 12:56:31 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 12:56:31 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã TNM: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: TNM
[28/500] Đang xử lý SBT...
OK: SBT
[29/500] Đang xử lý LLM...
OK: LLM
[30/500] Đang xử lý TMW...

2026-03-06 12:57:02 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 12:57:02 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 12:57:02 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã TMW: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: TMW
Nghỉ 25 giây giữa các batch...

=== Batch 31 - 35 ===
[31/500] Đang xử lý NBW...
OK: NBW
[32/500] Đang xử lý HPO...

2026-03-06 12:57:49 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 12:57:49 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 12:57:49 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã HPO: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: HPO
[33/500] Đang xử lý KSQ...
OK: KSQ
[34/500] Đang xử lý HSV...
OK: HSV
[35/500] Đang xử lý BTU...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP BTU: không có năm nào đủ 4 quý
SKIP: BTU
Nghỉ 25 giây giữa các batch...

=== Batch 36 - 40 ===
[36/500] Đang xử lý VXT...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP VXT: không có năm nào đủ 4 quý
SKIP: VXT
[37/500] Đang xử lý PXT...
OK: PXT
[38/500] Đang xử lý ANV...
OK: ANV
[39/500] Đang xử lý TNV...
SKIP TNV: không có Fraud hợp lệ
SKIP: TNV
[40/500] Đang xử lý CST...
OK: CST
Nghỉ 25 giây giữa các batch...

=== Batch 41 - 45 ===
[41/500] Đang xử lý TAW...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP TAW: không có năm nào đủ 4 quý
SKIP: TAW
[42/500] Đang xử lý NT2...

2026-03-06 13:00:33 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': Failed to fetch data: 502 - Bad Gateway
2026-03-06 13:00:33 - vnstock.common.data - ERROR - Error fetching income_statement: Failed to fetch data: 502 - Bad Gateway

Lỗi ở mã NT2: Failed to fetch data: 502 - Bad Gateway
SKIP: NT2
[43/500] Đang xử lý MWG...
OK: MWG
[44/500] Đang xử lý CFV...
OK: CFV
[45/500] Đang xử lý HWS...
OK: HWS
Nghỉ 25 giây giữa các batch...

=== Batch 46 - 50 ===
[46/500] Đang xử lý SSN...
OK: SSN
[47/500] Đang xử lý TNA...
OK: TNA
[48/500] Đang xử lý TNG...
OK: TNG
[49/500] Đang xử lý SJM...
SKIP SJM: không có Fraud hợp lệ
SKIP: SJM
[50/500] Đang xử lý GEX...
OK: GEX
Nghỉ 25 giây giữa các batch...

=== Batch 51 - 55 ===
[51/500] Đang xử lý FOX...
OK: FOX
[52/500] Đang xử lý MDA...

2026-03-06 13:03:14 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:03:14 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:03:14 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã MDA: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: MDA
[53/500] Đang xử lý HDW...
OK: HDW
[54/500] Đang xử lý IDP...
OK: IDP
[55/500] Đang xử lý EME...

2026-03-06 13:03:45 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:03:45 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:03:45 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã EME: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: EME
Nghỉ 25 giây giữa các batch...

=== Batch 56 - 60 ===
[56/500] Đang xử lý DTE...
OK: DTE
[57/500] Đang xử lý PEQ...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP PEQ: không có năm nào đủ 4 quý
SKIP: PEQ
[58/500] Đang xử lý IRC...
OK: IRC
[59/500] Đang xử lý CAD...
OK: CAD
[60/500] Đang xử lý VNL...
OK: VNL
Nghỉ 25 giây giữa các batch...

=== Batch 61 - 65 ===
[61/500] Đang xử lý KHP...
OK: KHP
[62/500] Đang xử lý PVV...
OK: PVV
[63/500] Đang xử lý PSH...
OK: PSH
[64/500] Đang xử lý PTP...

2026-03-06 13:06:21 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:06:21 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:06:21 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã PTP: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: PTP
[65/500] Đang xử lý VKC...
OK: VKC
Nghỉ 25 giây giữa các batch...

=== Batch 66 - 70 ===
[66/500] Đang xử lý HTN...
OK: HTN
[67/500] Đang xử lý IME...

2026-03-06 13:07:19 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:07:19 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:07:19 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã IME: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: IME
[68/500] Đang xử lý TCL...
OK: TCL
[69/500] Đang xử lý VIC...
OK: VIC
[70/500] Đang xử lý REE...
OK: REE
Nghỉ 25 giây giữa các batch...

=== Batch 71 - 75 ===
[71/500] Đang xử lý TUG...

2026-03-06 13:08:30 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:08:30 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:08:30 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã TUG: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: TUG
[72/500] Đang xử lý TNT...
OK: TNT
[73/500] Đang xử lý BCC...
OK: BCC
[74/500] Đang xử lý KDM...
OK: KDM
[75/500] Đang xử lý FDC...
OK: FDC
Nghỉ 25 giây giữa các batch...

=== Batch 76 - 80 ===
[76/500] Đang xử lý LEC...
OK: LEC
[77/500] Đang xử lý SCC...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP SCC: không có năm nào đủ 4 quý
SKIP: SCC
[78/500] Đang xử lý GTT...
OK: GTT
[79/500] Đang xử lý HLB...

2026-03-06 13:10:21 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:10:21 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:10:21 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã HLB: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: HLB
[80/500] Đang xử lý DST...
OK: DST
Nghỉ 25 giây giữa các batch...

=== Batch 81 - 85 ===
[81/500] Đang xử lý PTT...
OK: PTT
[82/500] Đang xử lý CCP...
OK: CCP
[83/500] Đang xử lý VCM...
OK: VCM
[84/500] Đang xử lý VCX...
OK: VCX
[85/500] Đang xử lý DCS...
OK: DCS
Nghỉ 25 giây giữa các batch...

=== Batch 86 - 90 ===
[86/500] Đang xử lý BT1...

2026-03-06 13:12:24 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:12:24 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:12:24 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã BT1: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: BT1
[87/500] Đang xử lý CDC...
OK: CDC
[88/500] Đang xử lý C92...
OK: C92
[89/500] Đang xử lý LKW...

2026-03-06 13:12:55 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:12:55 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:12:55 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã LKW: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: LKW
[90/500] Đang xử lý HBH...
OK: HBH
Nghỉ 25 giây giữa các batch...

=== Batch 91 - 95 ===
[91/500] Đang xử lý TDP...
OK: TDP
[92/500] Đang xử lý VFR...
OK: VFR
[93/500] Đang xử lý TLT...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP TLT: không có năm nào đủ 4 quý
SKIP: TLT
[94/500] Đang xử lý CTF...
OK: CTF
[95/500] Đang xử lý HPT...

2026-03-06 13:14:25 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:14:25 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:14:25 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã HPT: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: HPT
Nghỉ 25 giây giữa các batch...

=== Batch 96 - 100 ===
[96/500] Đang xử lý PHH...
OK: PHH
[97/500] Đang xử lý CNA...

2026-03-06 13:15:11 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:15:11 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:15:11 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã CNA: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: CNA
[98/500] Đang xử lý HLC...
OK: HLC
[99/500] Đang xử lý DOC...

2026-03-06 13:15:32 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:15:32 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:15:32 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã DOC: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: DOC
[100/500] Đang xử lý VLB...
OK: VLB
Nghỉ 25 giây giữa các batch...

=== Batch 101 - 105 ===
[101/500] Đang xử lý PVC...
OK: PVC
[102/500] Đang xử lý VHM...
OK: VHM
[103/500] Đang xử lý PTV...
OK: PTV
[104/500] Đang xử lý SAM...
OK: SAM
[105/500] Đang xử lý HSI...
SKIP HSI: không có Fraud hợp lệ
SKIP: HSI
Nghỉ 25 giây giữa các batch...

=== Batch 106 - 110 ===
[106/500] Đang xử lý SPV...

2026-03-06 13:17:35 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:17:35 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:17:35 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã SPV: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: SPV
[107/500] Đang xử lý VTH...
OK: VTH
[108/500] Đang xử lý VE9...
OK: VE9
[109/500] Đang xử lý KCB...
SKIP KCB: không có năm nào đủ 4 quý
SKIP: KCB
[110/500] Đang xử lý TTB...
OK: TTB
Nghỉ 25 giây giữa các batch...

=== Batch 111 - 115 ===
[111/500] Đang xử lý QCC...
SKIP QCC: không có Fraud hợp lệ
SKIP: QCC
[112/500] Đang xử lý PMJ...

2026-03-06 13:19:03 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:19:03 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:19:03 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã PMJ: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: PMJ
[113/500] Đang xử lý DTA...
OK: DTA
[114/500] Đang xử lý TBD...
OK: TBD
[115/500] Đang xử lý TSB...
OK: TSB
Nghỉ 25 giây giữa các batch...

=== Batch 116 - 120 ===
[116/500] Đang xử lý NLS...

2026-03-06 13:20:11 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:20:11 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:20:11 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã NLS: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: NLS
[117/500] Đang xử lý CII...
OK: CII
[118/500] Đang xử lý TMT...
OK: TMT
[119/500] Đang xử lý HAN...
OK: HAN
[120/500] Đang xử lý DDM...
OK: DDM
Nghỉ 25 giây giữa các batch...

=== Batch 121 - 125 ===
[121/500] Đang xử lý SGH...
OK: SGH
[122/500] Đang xử lý NET...
OK: NET
[123/500] Đang xử lý L45...

2026-03-06 13:21:55 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:21:55 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:21:55 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã L45: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: L45
[124/500] Đang xử lý TOT...
OK: TOT
[125/500] Đang xử lý RCD...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP RCD: không có năm nào đủ 4 quý
SKIP: RCD
Nghỉ 25 giây giữa các batch...

=== Batch 126 - 130 ===
[126/500] Đang xử lý VC5...
SKIP VC5: không có Fraud hợp lệ
SKIP: VC5
[127/500] Đang xử lý DNA...
OK: DNA
[128/500] Đang xử lý RAL...
OK: RAL
[129/500] Đang xử lý VSC...
OK: VSC
[130/500] Đang xử lý CC1...
OK: CC1
Nghỉ 25 giây giữa các batch...

=== Batch 131 - 135 ===
[131/500] Đang xử lý SDN...
OK: SDN
[132/500] Đang xử lý SP2...
OK: SP2
[133/500] Đang xử lý PMG...
OK: PMG
[134/500] Đang xử lý DSD...
OK: DSD
[135/500] Đang xử lý CCV...

2026-03-06 13:24:53 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:24:53 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:24:53 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã CCV: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: CCV
Nghỉ 25 giây giữa các batch...

=== Batch 136 - 140 ===
[136/500] Đang xử lý PXL...
OK: PXL
[137/500] Đang xử lý MFS...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP MFS: không có năm nào đủ 4 quý
SKIP: MFS
[138/500] Đang xử lý OIL...
OK: OIL
[139/500] Đang xử lý HAS...
OK: HAS
[140/500] Đang xử lý TVT...
OK: TVT
Nghỉ 25 giây giữa các batch...

=== Batch 141 - 145 ===
[141/500] Đang xử lý PSD...
OK: PSD
[142/500] Đang xử lý SHE...
OK: SHE
[143/500] Đang xử lý DSH...

2026-03-06 13:27:11 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:27:11 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:27:11 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã DSH: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: DSH
[144/500] Đang xử lý X77...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP X77: không có năm nào đủ 4 quý
SKIP: X77
[145/500] Đang xử lý VMS...
OK: VMS
Nghỉ 25 giây giữa các batch...

=== Batch 146 - 150 ===
[146/500] Đang xử lý CDG...
SKIP CDG: không có năm nào đủ 4 quý
SKIP: CDG
[147/500] Đang xử lý HTC...
OK: HTC
[148/500] Đang xử lý NAG...
OK: NAG
[149/500] Đang xử lý PTE...
OK: PTE
[150/500] Đang xử lý POV...
OK: POV
Nghỉ 25 giây giữa các batch...

=== Batch 151 - 155 ===
[151/500] Đang xử lý HD2...

2026-03-06 13:29:29 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:29:29 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:29:29 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã HD2: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: HD2
[152/500] Đang xử lý SKN...

2026-03-06 13:29:39 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:29:39 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:29:39 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã SKN: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: SKN
[153/500] Đang xử lý DTD...
OK: DTD
[154/500] Đang xử lý CPH...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP CPH: không có năm nào đủ 4 quý
SKIP: CPH
[155/500] Đang xử lý SD3...
OK: SD3
Nghỉ 25 giây giữa các batch...

=== Batch 156 - 160 ===
[156/500] Đang xử lý TBC...
OK: TBC
[157/500] Đang xử lý DAE...
OK: DAE
[158/500] Đang xử lý DHT...
OK: DHT
[159/500] Đang xử lý CAT...

2026-03-06 13:31:23 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:31:23 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:31:23 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã CAT: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: CAT
[160/500] Đang xử lý HID...
OK: HID
Nghỉ 25 giây giữa các batch...

=== Batch 161 - 165 ===
[161/500] Đang xử lý HPM...
OK: HPM
[162/500] Đang xử lý GCB...

2026-03-06 13:32:21 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:32:21 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:32:21 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã GCB: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: GCB
[163/500] Đang xử lý V12...
OK: V12
[164/500] Đang xử lý PTD...
OK: PTD
[165/500] Đang xử lý CHP...
OK: CHP
Nghỉ 25 giây giữa các batch...

=== Batch 166 - 170 ===
[166/500] Đang xử lý SIV...

2026-03-06 13:33:30 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:33:30 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:33:30 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã SIV: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: SIV
[167/500] Đang xử lý DWC...
OK: DWC
[168/500] Đang xử lý UDL...

2026-03-06 13:33:50 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:33:50 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:33:50 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã UDL: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: UDL
[169/500] Đang xử lý TID...
OK: TID
[170/500] Đang xử lý VHC...
OK: VHC
Nghỉ 25 giây giữa các batch...

=== Batch 171 - 175 ===
[171/500] Đang xử lý DMC...
OK: DMC
[172/500] Đang xử lý PSG...
SKIP PSG: không có Fraud hợp lệ
SKIP: PSG
[173/500] Đang xử lý VC6...
OK: VC6
[174/500] Đang xử lý XLV...

2026-03-06 13:35:22 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:35:22 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:35:22 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã XLV: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: XLV
[175/500] Đang xử lý BHP...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP BHP: không có năm nào đủ 4 quý
SKIP: BHP
Nghỉ 25 giây giữa các batch...

=== Batch 176 - 180 ===
[176/500] Đang xử lý DHN...

2026-03-06 13:36:10 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:36:10 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:36:10 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã DHN: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: DHN
[177/500] Đang xử lý MTS...
OK: MTS
[178/500] Đang xử lý TV2...
OK: TV2
[179/500] Đang xử lý MCH...
OK: MCH
[180/500] Đang xử lý EIC...
OK: EIC
Nghỉ 25 giây giữa các batch...

=== Batch 181 - 185 ===
[181/500] Đang xử lý FSO...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP FSO: không có Fraud hợp lệ
SKIP: FSO
[182/500] Đang xử lý VTP...
OK: VTP
[183/500] Đang xử lý TTE...
OK: TTE
[184/500] Đang xử lý DHA...
OK: DHA
[185/500] Đang xử lý BLN...

2026-03-06 13:38:17 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:38:17 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:38:17 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã BLN: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: BLN
Nghỉ 25 giây giữa các batch...

=== Batch 186 - 190 ===
[186/500] Đang xử lý MTP...

2026-03-06 13:38:53 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:38:53 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:38:53 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã MTP: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: MTP
[187/500] Đang xử lý CCL...
OK: CCL
[188/500] Đang xử lý ODE...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP ODE: không có năm nào đủ 4 quý
SKIP: ODE
[189/500] Đang xử lý FBC...

2026-03-06 13:39:26 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:39:26 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:39:26 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã FBC: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: FBC
[190/500] Đang xử lý EBS...
OK: EBS
Nghỉ 25 giây giữa các batch...

=== Batch 191 - 195 ===
[191/500] Đang xử lý GER...

2026-03-06 13:40:13 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:40:13 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:40:13 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã GER: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: GER
[192/500] Đang xử lý TIP...

2026-03-06 13:40:26 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': Failed to fetch data: 502 - Bad Gateway
2026-03-06 13:40:26 - vnstock.common.data - ERROR - Error fetching income_statement: Failed to fetch data: 502 - Bad Gateway

Lỗi ở mã TIP: Failed to fetch data: 502 - Bad Gateway
SKIP: TIP
[193/500] Đang xử lý TIX...
OK: TIX
[194/500] Đang xử lý BMK...

2026-03-06 13:40:48 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:40:48 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu cân đối kế toán': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:40:48 - vnstock.explorer.vci.financial - ERROR - Error retrieving balance sheet: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:40:48 - vnstock.common.data - ERROR - Error fetching balance_sheet: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã BMK: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: BMK
[195/500] Đang xử lý SHA...
Lỗi ở mã SHA: Failed to fetch data: 502 - Bad Gateway
SKIP: SHA
Nghỉ 25 giây giữa các batch...

=== Batch 196 - 200 ===
[196/500] Đang xử lý SZE...
OK: SZE
[197/500] Đang xử lý SHG...
OK: SHG
[198/500] Đang xử lý VNC...
OK: VNC
[199/500] Đang xử lý BTS...

2026-03-06 13:42:07 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu lưu chuyển tiền tệ': Failed to fetch data: 502 - Bad Gateway
2026-03-06 13:42:07 - vnstock.common.data - ERROR - Error fetching cash_flow: Failed to fetch data: 502 - Bad Gateway

Lỗi ở mã BTS: Failed to fetch data: 502 - Bad Gateway
SKIP: BTS
[200/500] Đang xử lý FRM...

2026-03-06 13:42:17 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:42:17 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:42:17 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã FRM: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: FRM
Nghỉ 25 giây giữa các batch...

=== Batch 201 - 205 ===
[201/500] Đang xử lý NHA...
OK: NHA
[202/500] Đang xử lý STD...
OK: STD
[203/500] Đang xử lý ANT...
OK: ANT
[204/500] Đang xử lý BHA...
OK: BHA
[205/500] Đang xử lý VIM...

2026-03-06 13:43:39 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:43:39 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:43:39 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã VIM: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: VIM
Nghỉ 25 giây giữa các batch...

=== Batch 206 - 210 ===
[206/500] Đang xử lý ABC...
OK: ABC
[207/500] Đang xử lý PGD...
OK: PGD
[208/500] Đang xử lý VE2...
OK: VE2
[209/500] Đang xử lý VTI...

2026-03-06 13:44:47 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:44:47 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:44:47 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã VTI: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: VTI
[210/500] Đang xử lý S72...
OK: S72
Nghỉ 25 giây giữa các batch...

=== Batch 211 - 215 ===
[211/500] Đang xử lý LSG...
OK: LSG
[212/500] Đang xử lý CCT...
OK: CCT
[213/500] Đang xử lý PSW...
OK: PSW
[214/500] Đang xử lý HNA...
OK: HNA
[215/500] Đang xử lý DNP...
OK: DNP
Nghỉ 25 giây giữa các batch...

=== Batch 216 - 220 ===
[216/500] Đang xử lý BNW...
OK: BNW
[217/500] Đang xử lý CAP...
OK: CAP
[218/500] Đang xử lý UIC...
OK: UIC
[219/500] Đang xử lý LTG...
OK: LTG
[220/500] Đang xử lý DVN...
OK: DVN
Nghỉ 25 giây giữa các batch...

=== Batch 221 - 225 ===
[221/500] Đang xử lý ND2...
OK: ND2
[222/500] Đang xử lý PTG...

2026-03-06 13:48:33 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:48:33 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:48:33 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã PTG: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: PTG
[223/500] Đang xử lý TCK...
OK: TCK
[224/500] Đang xử lý DTI...
OK: DTI
[225/500] Đang xử lý PDC...
OK: PDC
Nghỉ 25 giây giữa các batch...

=== Batch 226 - 230 ===
[226/500] Đang xử lý NDN...
OK: NDN
[227/500] Đang xử lý BMV...
OK: BMV
[228/500] Đang xử lý SII...
OK: SII
[229/500] Đang xử lý SVC...
OK: SVC
[230/500] Đang xử lý CIA...
OK: CIA
Nghỉ 25 giây giữa các batch...

=== Batch 231 - 235 ===
[231/500] Đang xử lý CSC...
OK: CSC
[232/500] Đang xử lý VGV...
OK: VGV
[233/500] Đang xử lý TCM...
OK: TCM
[234/500] Đang xử lý VPD...
OK: VPD
[235/500] Đang xử lý BNA...
OK: BNA
Nghỉ 25 giây giữa các batch...

=== Batch 236 - 240 ===
[236/500] Đang xử lý HMG...

2026-03-06 13:52:35 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:52:35 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:52:35 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã HMG: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: HMG
[237/500] Đang xử lý LTC...
SKIP LTC: không có Fraud hợp lệ
SKIP: LTC
[238/500] Đang xử lý CDR...

2026-03-06 13:52:57 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:52:57 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:52:57 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã CDR: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: CDR
[239/500] Đang xử lý A32...

2026-03-06 13:53:08 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:53:08 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:53:08 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã A32: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: A32
[240/500] Đang xử lý L61...
OK: L61
Nghỉ 25 giây giữa các batch...

=== Batch 241 - 245 ===
[241/500] Đang xử lý VWS...

2026-03-06 13:53:56 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:53:56 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:53:56 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã VWS: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: VWS
[242/500] Đang xử lý CH5...

2026-03-06 13:54:08 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:54:08 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:54:08 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã CH5: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: CH5
[243/500] Đang xử lý BMI...
Lỗi ở mã BMI: "Thiếu cột. Cần một trong ['Giá vốn hàng bán']"
SKIP: BMI
[244/500] Đang xử lý VES...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP VES: không có năm nào đủ 4 quý
SKIP: VES
[245/500] Đang xử lý HGM...
OK: HGM
Nghỉ 25 giây giữa các batch...

=== Batch 246 - 250 ===
[246/500] Đang xử lý HDG...
OK: HDG
[247/500] Đang xử lý TNB...
OK: TNB
[248/500] Đang xử lý GLC...
OK: GLC
[249/500] Đang xử lý KSV...
OK: KSV
[250/500] Đang xử lý MQB...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP MQB: không có năm nào đủ 4 quý
SKIP: MQB
Nghỉ 25 giây giữa các batch...

=== Batch 251 - 255 ===
[251/500] Đang xử lý UPC...

2026-03-06 13:56:36 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:56:36 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:56:36 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã UPC: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: UPC
[252/500] Đang xử lý TGP...

2026-03-06 13:56:48 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:56:48 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:56:48 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã TGP: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: TGP
[253/500] Đang xử lý HMR...
OK: HMR
[254/500] Đang xử lý D2D...
OK: D2D
[255/500] Đang xử lý VSA...
OK: VSA
Nghỉ 25 giây giữa các batch...

=== Batch 256 - 260 ===
[256/500] Đang xử lý DCH...

2026-03-06 13:57:56 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:57:56 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:57:56 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã DCH: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: DCH
[257/500] Đang xử lý HFC...

2026-03-06 13:58:07 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:58:07 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 13:58:07 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã HFC: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: HFC
[258/500] Đang xử lý VIW...
OK: VIW
[259/500] Đang xử lý CRC...
OK: CRC
[260/500] Đang xử lý EVG...
OK: EVG
Nghỉ 25 giây giữa các batch...

=== Batch 261 - 265 ===
[261/500] Đang xử lý VSH...
OK: VSH
[262/500] Đang xử lý NTB...
OK: NTB
[263/500] Đang xử lý AME...
OK: AME
[264/500] Đang xử lý ISG...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP ISG: không có năm nào đủ 4 quý
SKIP: ISG
[265/500] Đang xử lý L63...

2026-03-06 14:00:01 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:00:01 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:00:01 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã L63: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: L63
Nghỉ 25 giây giữa các batch...

=== Batch 266 - 270 ===
[266/500] Đang xử lý PIT...
OK: PIT
[267/500] Đang xử lý ECI...
OK: ECI
[268/500] Đang xử lý MST...
OK: MST
[269/500] Đang xử lý GTS...
OK: GTS
[270/500] Đang xử lý TVD...
OK: TVD
Nghỉ 25 giây giữa các batch...

=== Batch 271 - 275 ===
[271/500] Đang xử lý GMC...
OK: GMC
[272/500] Đang xử lý PVE...
OK: PVE
[273/500] Đang xử lý UMC...

2026-03-06 14:02:19 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:02:19 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:02:19 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã UMC: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: UMC
[274/500] Đang xử lý HVT...
OK: HVT
[275/500] Đang xử lý THB...
OK: THB
Nghỉ 25 giây giữa các batch...

=== Batch 276 - 280 ===
[276/500] Đang xử lý VMG...
OK: VMG
[277/500] Đang xử lý CKD...
OK: CKD
[278/500] Đang xử lý BQP...

2026-03-06 14:03:40 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:03:40 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu cân đối kế toán': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:03:40 - vnstock.explorer.vci.financial - ERROR - Error retrieving balance sheet: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:03:40 - vnstock.common.data - ERROR - Error fetching balance_sheet: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã BQP: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: BQP
[279/500] Đang xử lý ABS...
OK: ABS
[280/500] Đang xử lý MML...
OK: MML
Nghỉ 25 giây giữa các batch...

=== Batch 281 - 285 ===
[281/500] Đang xử lý THM...
SKIP THM: không có Fraud hợp lệ
SKIP: THM
[282/500] Đang xử lý SJS...
OK: SJS
[283/500] Đang xử lý BSH...
OK: BSH
[284/500] Đang xử lý HAR...
OK: HAR
[285/500] Đang xử lý ITQ...
OK: ITQ
Nghỉ 25 giây giữa các batch...

=== Batch 286 - 290 ===
[286/500] Đang xử lý TV4...
OK: TV4
[287/500] Đang xử lý VTE...
OK: VTE
[288/500] Đang xử lý PND...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP PND: không có năm nào đủ 4 quý
SKIP: PND
[289/500] Đang xử lý NTF...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP NTF: không có năm nào đủ 4 quý
SKIP: NTF
[290/500] Đang xử lý VHD...
OK: VHD
Nghỉ 25 giây giữa các batch...

=== Batch 291 - 295 ===
[291/500] Đang xử lý DVT...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
2026-03-06 14:07:31 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:07:31 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:07:31 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã DVT: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: DVT
[292/500] Đang xử lý CJC...
OK: CJC
[293/500] Đang xử lý VPH...
OK: VPH
[294/500] Đang xử lý CLL...
OK: CLL
[295/500] Đang xử lý GMA...
OK: GMA
Nghỉ 25 giây giữa các batch...

=== Batch 296 - 300 ===
[296/500] Đang xử lý VDT...

2026-03-06 14:08:52 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:08:52 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:08:52 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã VDT: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: VDT
[297/500] Đang xử lý SD8...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP SD8: không có năm nào đủ 4 quý
SKIP: SD8
[298/500] Đang xử lý TV6...

2026-03-06 14:09:15 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:09:15 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:09:15 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã TV6: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: TV6
[299/500] Đang xử lý VQC...
SKIP VQC: không có Fraud hợp lệ
SKIP: VQC
[300/500] Đang xử lý GND...

2026-03-06 14:09:38 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:09:38 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:09:38 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã GND: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: GND
Nghỉ 25 giây giữa các batch...

=== Batch 301 - 305 ===
[301/500] Đang xử lý BFC...
OK: BFC
[302/500] Đang xử lý TRA...
OK: TRA
[303/500] Đang xử lý TDW...
OK: TDW
[304/500] Đang xử lý ICF...
OK: ICF
[305/500] Đang xử lý PET...
OK: PET
Nghỉ 25 giây giữa các batch...

=== Batch 306 - 310 ===
[306/500] Đang xử lý NHT...
OK: NHT
[307/500] Đang xử lý FCM...
OK: FCM
[308/500] Đang xử lý VIP...
OK: VIP
[309/500] Đang xử lý THS...
OK: THS
[310/500] Đang xử lý TDB...

2026-03-06 14:12:25 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:12:25 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:12:25 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã TDB: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: TDB
Nghỉ 25 giây giữa các batch...

=== Batch 311 - 315 ===
[311/500] Đang xử lý SZL...
OK: SZL
[312/500] Đang xử lý TDG...
OK: TDG
[313/500] Đang xử lý VRC...
OK: VRC
[314/500] Đang xử lý TDF...
OK: TDF
[315/500] Đang xử lý CYC...
SKIP CYC: không có Fraud hợp lệ
SKIP: CYC
Nghỉ 25 giây giữa các batch...

=== Batch 316 - 320 ===
[316/500] Đang xử lý C69...
OK: C69
[317/500] Đang xử lý PVI...
Lỗi ở mã PVI: "Thiếu cột. Cần một trong ['Giá vốn hàng bán']"
SKIP: PVI
[318/500] Đang xử lý DKC...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP DKC: không có năm nào đủ 4 quý
SKIP: DKC
[319/500] Đang xử lý UDC...
OK: UDC
[320/500] Đang xử lý CLH...
OK: CLH
Nghỉ 25 giây giữa các batch...

=== Batch 321 - 325 ===
[321/500] Đang xử lý MVB...
OK: MVB
[322/500] Đang xử lý HHS...
OK: HHS
[323/500] Đang xử lý FT1...

2026-03-06 14:16:30 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:16:30 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:16:30 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã FT1: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: FT1
[324/500] Đang xử lý BHG...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP BHG: không có năm nào đủ 4 quý
SKIP: BHG
[325/500] Đang xử lý SMA...
OK: SMA
Nghỉ 25 giây giữa các batch...

=== Batch 326 - 330 ===
[326/500] Đang xử lý G20...
OK: G20
[327/500] Đang xử lý DP2...
OK: DP2
[328/500] Đang xử lý VID...
OK: VID
[329/500] Đang xử lý NFC...
OK: NFC
[330/500] Đang xử lý MTL...

2026-03-06 14:18:18 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:18:18 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:18:18 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã MTL: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: MTL
Nghỉ 25 giây giữa các batch...

=== Batch 331 - 335 ===
[331/500] Đang xử lý PIA...
OK: PIA
[332/500] Đang xử lý VFC...
OK: VFC
[333/500] Đang xử lý FRC...

2026-03-06 14:19:18 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:19:18 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:19:18 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã FRC: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: FRC
[334/500] Đang xử lý PCC...

2026-03-06 14:19:29 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:19:29 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:19:29 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã PCC: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: PCC
[335/500] Đang xử lý CNT...
OK: CNT
Nghỉ 25 giây giữa các batch...

=== Batch 336 - 340 ===
[336/500] Đang xử lý SJD...
OK: SJD
[337/500] Đang xử lý BHK...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP BHK: không có năm nào đủ 4 quý
SKIP: BHK
[338/500] Đang xử lý M10...
OK: M10
[339/500] Đang xử lý S55...
OK: S55
[340/500] Đang xử lý GEL...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP GEL: không có Fraud hợp lệ
SKIP: GEL
Nghỉ 25 giây giữa các batch...

=== Batch 341 - 345 ===
[341/500] Đang xử lý DP1...
OK: DP1
[342/500] Đang xử lý NLG...
OK: NLG
[343/500] Đang xử lý L43...
OK: L43
[344/500] Đang xử lý HAF...
OK: HAF
[345/500] Đang xử lý PQN...
OK: PQN
Nghỉ 25 giây giữa các batch...

=== Batch 346 - 350 ===
[346/500] Đang xử lý C47...
OK: C47
[347/500] Đang xử lý SID...
OK: SID
[348/500] Đang xử lý PC1...
OK: PC1
[349/500] Đang xử lý POS...
OK: POS
[350/500] Đang xử lý PSN...
OK: PSN
Nghỉ 25 giây giữa các batch...

=== Batch 351 - 355 ===
[351/500] Đang xử lý VBG...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP VBG: không có năm nào đủ 4 quý
SKIP: VBG
[352/500] Đang xử lý NBP...
OK: NBP
[353/500] Đang xử lý CCR...
OK: CCR
[354/500] Đang xử lý BAF...
OK: BAF
[355/500] Đang xử lý HMC...
OK: HMC
Nghỉ 25 giây giữa các batch...

=== Batch 356 - 360 ===
[356/500] Đang xử lý BBH...

2026-03-06 14:28:31 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:28:31 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:28:31 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã BBH: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: BBH
[357/500] Đang xử lý GVT...
SKIP GVT: không có Fraud hợp lệ
SKIP: GVT
[358/500] Đang xử lý NWT...

2026-03-06 14:29:04 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:29:04 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:29:04 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã NWT: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: NWT
[359/500] Đang xử lý PMW...
OK: PMW
[360/500] Đang xử lý BMD...

2026-03-06 14:29:39 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:29:39 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:29:39 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã BMD: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: BMD
Nghỉ 25 giây giữa các batch...

=== Batch 361 - 365 ===
[361/500] Đang xử lý DC1...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP DC1: không có năm nào đủ 4 quý
SKIP: DC1
[362/500] Đang xử lý SCL...
OK: SCL
[363/500] Đang xử lý F88...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP F88: không có năm nào đủ 4 quý
SKIP: F88
[364/500] Đang xử lý AMP...
OK: AMP
[365/500] Đang xử lý MBG...
OK: MBG
Nghỉ 25 giây giữa các batch...

=== Batch 366 - 370 ===
[366/500] Đang xử lý VGC...
OK: VGC
[367/500] Đang xử lý MBT...

2026-03-06 14:32:06 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:32:06 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:32:06 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã MBT: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: MBT
[368/500] Đang xử lý GMD...
OK: GMD
[369/500] Đang xử lý VIF...
OK: VIF
[370/500] Đang xử lý EGL...

2026-03-06 14:32:41 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:32:41 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:32:41 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã EGL: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: EGL
Nghỉ 25 giây giữa các batch...

=== Batch 371 - 375 ===
[371/500] Đang xử lý VFG...
OK: VFG
[372/500] Đang xử lý VTM...

2026-03-06 14:33:28 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:33:28 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:33:28 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã VTM: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: VTM
[373/500] Đang xử lý GDA...
OK: GDA
[374/500] Đang xử lý PHN...
OK: PHN
[375/500] Đang xử lý PSC...
OK: PSC
Nghỉ 25 giây giữa các batch...

=== Batch 376 - 380 ===
[376/500] Đang xử lý TLD...
OK: TLD
[377/500] Đang xử lý SDT...
OK: SDT
[378/500] Đang xử lý SDA...
OK: SDA
[379/500] Đang xử lý HAT...
OK: HAT
[380/500] Đang xử lý IST...
OK: IST
Nghỉ 25 giây giữa các batch...

=== Batch 381 - 385 ===
[381/500] Đang xử lý BVG...
SKIP BVG: không có Fraud hợp lệ
SKIP: BVG
[382/500] Đang xử lý SD2...
OK: SD2
[383/500] Đang xử lý HU3...
OK: HU3
[384/500] Đang xử lý VC2...
OK: VC2
[385/500] Đang xử lý HTM...
OK: HTM
Nghỉ 25 giây giữa các batch...

=== Batch 386 - 390 ===
[386/500] Đang xử lý BRS...
SKIP BRS: không có năm nào đủ 4 quý
SKIP: BRS
[387/500] Đang xử lý VGL...
SKIP VGL: không có năm nào đủ 4 quý
SKIP: VGL
[388/500] Đang xử lý VHL...
OK: VHL
[389/500] Đang xử lý PNP...
OK: PNP
[390/500] Đang xử lý NBE...

2026-03-06 14:38:04 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:38:04 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:38:04 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã NBE: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: NBE
Nghỉ 25 giây giữa các batch...

=== Batch 391 - 395 ===
[391/500] Đang xử lý PNT...

2026-03-06 14:38:39 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:38:39 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:38:39 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã PNT: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: PNT
[392/500] Đang xử lý KTL...
OK: KTL
[393/500] Đang xử lý TLH...
OK: TLH
[394/500] Đang xử lý VCE...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP VCE: không có năm nào đủ 4 quý
SKIP: VCE
[395/500] Đang xử lý SRC...
OK: SRC
Nghỉ 25 giây giữa các batch...

=== Batch 396 - 400 ===
[396/500] Đang xử lý TIE...
OK: TIE
[397/500] Đang xử lý SCD...
OK: SCD
[398/500] Đang xử lý C21...
OK: C21
[399/500] Đang xử lý SIG...

2026-03-06 14:40:32 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:40:32 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:40:32 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã SIG: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: SIG
[400/500] Đang xử lý TBR...

2026-03-06 14:40:43 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:40:43 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:40:43 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã TBR: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: TBR
Nghỉ 25 giây giữa các batch...

=== Batch 401 - 405 ===
[401/500] Đang xử lý L10...
OK: L10
[402/500] Đang xử lý VDB...

2026-03-06 14:41:30 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:41:30 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:41:30 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã VDB: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: VDB
[403/500] Đang xử lý SLD...
OK: SLD
[404/500] Đang xử lý FCS...
OK: FCS
[405/500] Đang xử lý QBS...
Lỗi ở mã QBS: Failed to fetch data: 502 - Bad Gateway
SKIP: QBS
Nghỉ 25 giây giữa các batch...

=== Batch 406 - 410 ===
[406/500] Đang xử lý CMP...
OK: CMP
[407/500] Đang xử lý VC3...
OK: VC3
[408/500] Đang xử lý ICT...
OK: ICT
[409/500] Đang xử lý BHH...

2026-03-06 14:43:09 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:43:09 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu cân đối kế toán': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:43:09 - vnstock.explorer.vci.financial - ERROR - Error retrieving balance sheet: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:43:09 - vnstock.common.data - ERROR - Error fetching balance_sheet: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã BHH: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: BHH
[410/500] Đang xử lý PGN...
OK: PGN
Nghỉ 25 giây giữa các batch...

=== Batch 411 - 415 ===
[411/500] Đang xử lý SBR...
OK: SBR
[412/500] Đang xử lý MQN...

2026-03-06 14:44:09 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:44:09 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:44:09 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã MQN: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: MQN
[413/500] Đang xử lý HT1...
OK: HT1
[414/500] Đang xử lý LSS...
OK: LSS
[415/500] Đang xử lý PHP...
OK: PHP
Nghỉ 25 giây giữa các batch...

=== Batch 416 - 420 ===
[416/500] Đang xử lý HJC...
OK: HJC
[417/500] Đang xử lý VLC...
OK: VLC
[418/500] Đang xử lý DAG...
OK: DAG
[419/500] Đang xử lý CPI...
OK: CPI
[420/500] Đang xử lý TRS...

2026-03-06 14:46:07 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:46:07 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:46:07 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã TRS: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: TRS
Nghỉ 25 giây giữa các batch...

=== Batch 421 - 425 ===
[421/500] Đang xử lý PLX...
OK: PLX
[422/500] Đang xử lý SHI...
OK: SHI
[423/500] Đang xử lý SBL...
OK: SBL
[424/500] Đang xử lý DFC...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP DFC: không có năm nào đủ 4 quý
SKIP: DFC
[425/500] Đang xử lý BWS...
OK: BWS
Nghỉ 25 giây giữa các batch...

=== Batch 426 - 430 ===
[426/500] Đang xử lý TDC...
OK: TDC
[427/500] Đang xử lý PSE...
OK: PSE
[428/500] Đang xử lý MA1...

2026-03-06 14:48:25 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:48:25 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:48:25 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã MA1: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: MA1
[429/500] Đang xử lý VDL...
OK: VDL
[430/500] Đang xử lý QNC...
OK: QNC
Nghỉ 25 giây giữa các batch...

=== Batch 431 - 435 ===
[431/500] Đang xử lý ALC...
OK: ALC
[432/500] Đang xử lý TSD...

2026-03-06 14:49:32 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:49:32 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:49:32 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã TSD: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: TSD
[433/500] Đang xử lý DSP...
OK: DSP
[434/500] Đang xử lý SGR...
OK: SGR
[435/500] Đang xử lý CIG...
OK: CIG
Nghỉ 25 giây giữa các batch...

=== Batch 436 - 440 ===
[436/500] Đang xử lý MKP...
OK: MKP
[437/500] Đang xử lý ONW...

2026-03-06 14:50:50 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:50:50 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:50:50 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã ONW: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: ONW
[438/500] Đang xử lý ILS...
OK: ILS
[439/500] Đang xử lý SFG...
OK: SFG
[440/500] Đang xử lý DXS...
OK: DXS
Nghỉ 25 giây giữa các batch...

=== Batch 441 - 445 ===
[441/500] Đang xử lý DNL...

2026-03-06 14:51:59 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:51:59 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:51:59 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã DNL: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: DNL
[442/500] Đang xử lý CEO...
OK: CEO
[443/500] Đang xử lý PPS...
OK: PPS
[444/500] Đang xử lý HNP...

2026-03-06 14:52:35 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:52:35 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:52:35 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã HNP: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: HNP
[445/500] Đang xử lý VTO...
OK: VTO
Nghỉ 25 giây giữa các batch...

=== Batch 446 - 450 ===
[446/500] Đang xử lý DPC...
OK: DPC
[447/500] Đang xử lý SHN...
OK: SHN
[448/500] Đang xử lý TQN...

2026-03-06 14:53:45 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:53:45 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:53:45 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã TQN: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: TQN
[449/500] Đang xử lý LQN...

2026-03-06 14:53:57 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:53:57 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:53:57 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã LQN: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: LQN
[450/500] Đang xử lý VCS...
OK: VCS
Nghỉ 25 giây giữa các batch...

=== Batch 451 - 455 ===
[451/500] Đang xử lý HSP...
OK: HSP
[452/500] Đang xử lý STS...

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

SKIP STS: không có năm nào đủ 4 quý
SKIP: STS
[453/500] Đang xử lý VBC...
OK: VBC
[454/500] Đang xử lý ELC...
OK: ELC
[455/500] Đang xử lý HSL...
OK: HSL
Nghỉ 25 giây giữa các batch...

=== Batch 456 - 460 ===
[456/500] Đang xử lý HCT...
OK: HCT
[457/500] Đang xử lý TRC...
OK: TRC
[458/500] Đang xử lý MSH...
OK: MSH
[459/500] Đang xử lý GDT...
OK: GDT
[460/500] Đang xử lý SDK...
OK: SDK
Nghỉ 25 giây giữa các batch...

=== Batch 461 - 465 ===
[461/500] Đang xử lý CCA...
OK: CCA
[462/500] Đang xử lý G36...
OK: G36
[463/500] Đang xử lý HAV...

2026-03-06 14:57:39 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:57:39 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu cân đối kế toán': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:57:39 - vnstock.explorer.vci.financial - ERROR - Error retrieving balance sheet: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:57:39 - vnstock.common.data - ERROR - Error fetching balance_sheet: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã HAV: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: HAV
[464/500] Đang xử lý MTA...
OK: MTA
[465/500] Đang xử lý VNI...
SKIP VNI: không có Fraud hợp lệ
SKIP: VNI
Nghỉ 25 giây giữa các batch...

=== Batch 466 - 470 ===
[466/500] Đang xử lý NAV...
OK: NAV
[467/500] Đang xử lý LM8...
OK: LM8
[468/500] Đang xử lý DNT...

2026-03-06 14:58:58 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:58:58 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
2026-03-06 14:58:58 - vnstock.common.data - ERROR - Error fetching income_statement: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"

Lỗi ở mã DNT: "None of [Index(['CP', 'Năm', 'Kỳ'], dtype='object')] are in the [columns]"
SKIP: DNT
[469/500] Đang xử lý VNP...
OK: VNP
[470/500] Đang xử lý CRV...
OK: CRV
Nghỉ 25 giây giữa các batch...

=== Batch 471 - 475 ===
[471/500] Đang xử lý SSG...
SKIP SSG: không có Fraud hợp lệ
SKIP: SSG
[472/500] Đang xử lý DAH...
OK: DAH
[473/500] Đang xử lý DVM...

2026-03-06 15:00:19 - vnstock.explorer.vci.financial - ERROR - Error processing financial report data: Failed to fetch data: 502 - Bad Gateway
2026-03-06 15:00:19 - vnstock.explorer.vci.financial - ERROR - Error processing report 'Chỉ tiêu kết quả kinh doanh': Failed to fetch data: 502 - Bad Gateway
2026-03-06 15:00:19 - vnstock.common.data - ERROR - Error fetching income_statement: Failed to fetch data: 502 - Bad Gateway

Lỗi ở mã DVM: Failed to fetch data: 502 - Bad Gateway
SKIP: DVM
[474/500] Đang xử lý SPC...
OK: SPC
[475/500] Đang xử lý SBB...
OK: SBB
Nghỉ 25 giây giữa các batch...

=== Batch 476 - 480 ===
[476/500] Đang xử lý MCG...
OK: MCG
[477/500] Đang xử lý SDU...
OK: SDU
[478/500] Đang xử lý VGR...
OK: VGR
[479/500] Đang xử lý HOM...
OK: HOM
[480/500] Đang xử lý AGP...
OK: AGP
Nghỉ 25 giây giữa các batch...

=== Batch 481 - 485 ===
[481/500] Đang xử lý MCF...
OK: MCF
[482/500] Đang xử lý VGG...
OK: VGG
[483/500] Đang xử lý PJT...
OK: PJT
[484/500] Đang xử lý SBV...
OK: SBV
[485/500] Đang xử lý BSQ...
OK: BSQ
Nghỉ 25 giây giữa các batch...

=== Batch 486 - 490 ===
[486/500] Đang xử lý MAC...
OK: MAC
[487/500] Đang xử lý DLD...
OK: DLD
[488/500] Đang xử lý TMP...
OK: TMP
[489/500] Đang xử lý BTT...
OK: BTT
[490/500] Đang xử lý PVH...
OK: PVH
Nghỉ 25 giây giữa các batch...

=== Batch 491 - 495 ===
[491/500] Đang xử lý CTT...
OK: CTT
[492/500] Đang xử lý VE1...
OK: VE1
[493/500] Đang xử lý VTG...
OK: VTG
[494/500] Đang xử lý HTG...
OK: HTG
[495/500] Đang xử lý DBD...
OK: DBD
Nghỉ 25 giây giữa các batch...

=== Batch 496 - 500 ===
[496/500] Đang xử lý LO5...
OK: LO5
[497/500] Đang xử lý GCF...
OK: GCF
[498/500] Đang xử lý TMG...
OK: TMG
[499/500] Đang xử lý TKC...
OK: TKC
[500/500] Đang xử lý TAR...
OK: TAR
Số dòng: 2237 | Số cột: 34
Số mã lỗi/bỏ qua: 146
Danh sách mã lỗi: ['VKP', 'DMS', 'POB', 'ACE', 'TRV', 'PVO', 'GTD', 'BSD', 'MGC', 'VMT', 'TNM', 'TMW', 'HPO', 'BTU', 'VXT', 'TNV', 'TAW', 'NT2', 'SJM', 'MDA', 'EME', 'PEQ', 'PTP', 'IME', 'TUG', 'SCC', 'HLB', 'BT1', 'LKW', 'TLT', 'HPT', 'CNA', 'DOC', 'HSI', 'SPV', 'KCB', 'QCC', 'PMJ', 'NLS', 'L45', 'RCD', 'VC5', 'CCV', 'MFS', 'DSH', 'X77', 'CDG', 'HD2', 'SKN', 'CPH', 'CAT', 'GCB', 'SIV', 'UDL', 'PSG', 'XLV', 'BHP', 'DHN', 'FSO', 'BLN', 'MTP', 'ODE', 'FBC', 'GER', 'TIP', 'BMK', 'SHA', 'BTS', 'FRM', 'VIM', 'VTI', 'PTG', 'HMG', 'LTC', 'CDR', 'A32', 'VWS', 'CH5', 'BMI', 'VES', 'MQB', 'UPC', 'TGP', 'DCH', 'HFC', 'ISG', 'L63', 'UMC', 'BQP', 'THM', 'PND', 'NTF', 'DVT', 'VDT', 'SD8', 'TV6', 'VQC', 'GND', 'TDB', 'CYC', 'PVI', 'DKC', 'FT1', 'BHG', 'MTL', 'FRC', 'PCC', 'BHK', 'GEL', 'VBG', 'BBH', 'GVT', 'NWT', 'BMD', 'DC1', 'F88', 'MBT', 'EGL', 'VTM', 'BVG', 'BRS', 'VGL', 'NBE', 'PNT', 'VCE', 'SIG', 'TBR', 'VDB', 'QBS', 'BHH', 'MQN', 'TRS', 'DFC', 'MA1', 'TSD', 'ONW', 'DNL', 'HNP', 'TQN', 'LQN', 'STS', 'HAV', 'VNI', 'DNT', 'SSG', 'DVM']

,CP,Năm,DSRI,GMI,AQI,SGI,DEPI,SGAI,LVGI,TATA,RSST_Accruals,Delta_Receivables,Delta_Inventory,Delta_Cash_Sales,Delta_ROA,Soft_Assets,ROA,ROE,Net_Profit_Margin,Gross_Profit_Margin,Sales_Growth,Revenue_Growth,Debt_to_Assets,Debt_to_Equity,Receivables_to_Revenue,Receivables_to_Assets,Inventory_to_Assets,Current_Assets_to_Total_Assets,CFO_to_Assets,CFO_to_Revenue,Accruals_to_Assets,Working_Capital_to_Assets,Firm_Size,Fraud
0,VGI,2018,1.084421,1.046653,1.029731,0.886654,0.884559,0.959822,0.889766,-0.101945,0.081258,-0.004828,-0.006006,-1.876824e+12,-0.011918,0.707667,-0.018295,-0.042918,-0.062762,1.685693,-0.113346,-0.113346,0.573722,1.345887,0.413736,0.120602,0.061870,0.397922,0.083650,0.286968,-0.101945,0.090983,31.689111,1
1,VGI,2019,1.222105,1.025861,1.188574,1.014058,0.893106,1.602671,0.916363,-0.104717,0.053417,0.027434,-0.015394,-1.432731e+12,0.007769,0.744110,-0.010526,-0.022194,-0.037457,1.643199,0.014058,0.014058,0.525738,1.108537,0.505629,0.142082,0.043422,0.377742,0.094191,0.335201,-0.104717,0.107275,31.739738,1
2,VGI,2020,1.236499,1.009898,0.840532,1.108642,0.882174,0.804994,0.939260,-0.099576,0.014291,0.054354,-0.008548,-1.348879e+12,0.020008,0.739801,0.009483,0.018733,0.029507,1.627093,0.108642,0.108642,0.493805,0.975521,0.625210,0.200925,0.036246,0.449080,0.109058,0.339352,-0.099576,0.164019,31.708628,1
3,VGI,2021,1.155991,0.998356,0.733941,1.014753,1.000687,1.038066,0.927906,-0.104996,-0.045378,0.038817,-0.006047,-1.771774e+12,-0.016420,0.707255,-0.006937,-0.012804,-0.019054,1.629773,0.014753,0.014753,0.458204,0.845713,0.722737,0.263135,0.034418,0.550051,0.098059,0.269334,-0.104996,0.235904,31.598499,1
4,VGI,2022,0.853202,1.060896,0.427161,1.228021,1.077639,1.332037,0.919541,-0.255044,-0.023831,0.013201,0.008661,3.723540e+12,0.023518,0.645530,0.016581,0.028654,0.035297,1.536223,0.228021,0.228021,0.421337,0.728122,0.616641,0.289664,0.044822,0.684917,0.271625,0.578238,-0.255044,0.355199,31.549087,0
5,VGI,2023,0.623139,1.028082,0.704973,1.193931,1.088641,1.001802,0.992860,-0.231613,0.007751,-0.071103,0.006868,8.312910e+12,-0.004715,0.628832,0.011866,0.020399,0.022066,1.494261,0.193931,0.193931,0.418329,0.719185,0.384253,0.206628,0.049844,0.715537,0.243479,0.452783,-0.231613,0.370481,31.591156,1
6,VGI,2024,0.582211,1.000351,0.624938,1.253632,1.036709,0.749344,1.040260,-0.168717,0.014031,-0.046159,0.002815,1.008378e+13,0.076821,0.608035,0.088687,0.157015,0.159077,1.493737,0.253632,0.253632,0.435171,0.770447,0.223716,0.124724,0.044036,0.767365,0.257404,0.461704,-0.168717,0.411129,31.781095,0
7,AGM,2018,1.097927,1.008271,1.340456,0.919842,0.788457,1.078348,0.633748,-0.142846,0.178462,0.001030,-0.093549,-1.812426e+11,0.033978,0.702721,0.049644,0.072620,0.013214,1.924617,-0.080158,-0.080158,0.316386,0.462813,0.027918,0.104887,0.493065,0.732636,0.192490,0.051235,-0.142846,0.426104,27.036548,0
8,AGM,2019,1.697592,1.004943,1.688193,1.022351,1.126884,1.092261,1.353827,0.044612,0.103092,0.055144,-0.025324,3.766470e+09,0.002535,0.793577,0.052179,0.091275,0.019006,1.915151,0.022351,0.022351,0.428332,0.749266,0.047393,0.130115,0.327108,0.765501,0.007567,0.002756,0.044612,0.343888,27.372331,0
9,AGM,2020,0.944123,0.996805,0.994262,0.924767,1.047376,1.006677,0.983765,-0.052108,-0.095748,-0.016805,-0.048992,-1.467196e+11,-0.019574,0.699084,0.032605,0.056349,0.012618,1.921290,-0.075233,-0.075233,0.421378,0.728243,0.044745,0.115618,0.283918,0.765717,0.084713,0.032785,-0.052108,0.349656,27.354748,0
10,AGM,2021,4.431094,0.990195,1.920958,2.002288,2.461936,0.791724,1.756156,0.377641,-0.060974,0.371936,-0.001847,1.274195e+12,-0.008519,0.722354,0.024085,0.092638,0.011392,1.940315,1.002288,1.002288,0.740005,2.846230,0.198269,0.419182,0.114173,0.701062,-0.353556,-0.167229,0.377641,0.146470,28.249669,0
11,AGM,2022,0.782277,0.996233,0.651861,0.873882,1.292594,1.843774,1.101715,-0.111883,0.017343,-0.155745,-0.052679,-2.487905e+11,-0.172215,0.584067,-0.148129,-0.801890,-0.068272,1.947651,-0.126118,-0.126118,0.815275,4.413449,0.155102,0.336523,0.081401,0.495938,-0.036247,-0.016706,-0.111883,-0.154930,28.088952,1
12,AGM,2023,2.308373,0.985751,3.787267,0.229737,0.584957,1.444271,1.204939,-0.260761,-0.189024,-0.201974,-0.083739,-2.392027e+12,-0.025604,0.633536,-0.173733,-9.846789,-0.272756,1.975805,-0.770263,-0.770263,0.982356,55.677676,0.358032,0.228050,0.020279,0.278825,0.087028,0.136632,-0.260761,-0.676920,27.843775,0
13,AGM,2024,1.818232,0.971177,1.066486,0.305750,1.396361,3.897477,1.257274,-0.242094,-0.232175,-0.120824,-0.014304,-4.217630e+11,-0.076818,0.566578,-0.250551,1.065764,-1.078345,2.034443,-0.694250,-0.694250,1.235091,-5.253678,0.650986,0.151255,0.009890,0.187483,-0.008457,-0.036398,-0.242094,-1.033762,27.667249,0
14,BKC,2018,0.841932,0.952255,1.080715,0.987486,0.537917,0.965435,1.197318,0.088754,0.024237,-0.015932,0.221419,2.416639e+09,-0.041721,0.692532,-0.030459,-0.063284,-0.049804,1.942070,-0.012514,-0.012514,0.518703,1.077719,0.128463,0.078563,0.413480,0.504713,-0.119212,-0.194930,0.088754,-0.005270,26.411455,0
15,BKC,2019,3.762306,1.024018,0.710309,1.302028,0.878264,0.677434,1.101589,0.179879,0.031758,0.250268,-0.033412,-3.590942e+10,0.065795,0.764265,0.035336,0.082446,0.054311,1.896520,0.302028,0.302028,0.571397,1.333164,0.483316,0.314461,0.304441,0.637453,-0.144542,-0.222156,0.179879,0.079887,26.613453,1
16,BKC,2020,1.168800,0.954227,0.743379,0.912872,1.205292,0.920941,1.155882,0.022973,-0.058501,0.019594,0.068157,-2.810308e+10,-0.094622,0.778143,-0.059285,-0.174609,-0.107271,1.987493,-0.087128,-0.087128,0.660468,1.945228,0.564899,0.312203,0.351442,0.682432,-0.082258,-0.148838,0.022973,0.047707,26.685480,0
17,BKC,2021,0.898459,1.035419,0.828253,1.760504,0.772787,0.635817,1.025105,-0.042941,-0.017791,0.167017,-0.061265,9.272237e+10,0.070007,0.805823,0.010721,0.033198,0.011983,1.919507,0.760504,0.760504,0.677049,2.096442,0.507539,0.454115,0.261916,0.754716,0.053662,0.059975,-0.042941,0.101339,26.769309,1
18,BKC,2022,0.708985,0.997861,2.222275,0.635759,0.864730,1.640592,0.794470,-0.161658,0.126798,-0.273650,0.152304,-3.230604e+10,-0.003012,0.852838,0.007709,0.016683,0.012353,1.923621,-0.364241,-0.364241,0.537895,1.164009,0.359838,0.224569,0.439657,0.678653,0.169367,0.271386,-0.161658,0.166729,26.676620,1
19,BKC,2023,0.505579,0.996200,0.684790,1.830849,1.106246,0.677631,0.935451,-0.073258,-0.049576,-0.017451,-0.062882,2.060820e+11,0.006211,0.774121,0.013920,0.028019,0.011658,1.930958,0.830849,0.830849,0.503174,1.012778,0.181926,0.217226,0.396565,0.722837,0.087178,0.073012,-0.073258,0.302142,26.632592,1

In [ ]:
# Lưu dataset ra file Excel
output_file = "financial_fraud_dataset.xlsx"

all_data.to_excel(output_file, index=False)

print(f"Đã lưu file: {output_file}")
print("Kích thước dữ liệu:", all_data.shape)

Đã lưu file: financial_fraud_dataset.xlsx
Kích thước dữ liệu: (2237, 34)